apiVersion: ENC[AES256_GCM,data:LGc=,iv:6qSddOaylKwAzc9GdfcKbvjihH+YLt95S0auL94DgHw=,tag:ax6ZcERotQiE4OKZ6lc1ow==,type:str]
kind: ENC[AES256_GCM,data:Vt5OQ4hh,iv:iRgqePyFeTnR9UUFEWQT32bV4hF9JFcSHj9ADUHyF+k=,tag:LOHW2HzXDrnfVTuFU44usQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dbg96INGyjSqx1QAn9r+uodv,iv:XYGdcKXf63pGmCXodXpdzaOHiRjf+OztBBmwo2/4/XI=,tag:oH3h1LKpZ7Q+dxYVnYj9yg==,type:str]
    namespace: ENC[AES256_GCM,data:5huCiE9NqnLaPw==,iv:SktUMmILA/dCZDJgSUKajeAQpLFkJ1nM++x0J0ZQB0A=,tag:lvTGFtrpGnsZGAZDoWRANQ==,type:str]
type: ENC[AES256_GCM,data:Rs4pfEePj+DUpErXxRkvOankkh8dRT0X,iv:YtnvnrRXNCnYdcCKokyax5UC64Bsk6F91qcD7G5SmI0=,tag:PE7sHPMSDCT2oxl4bYmsNA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:lpjf,iv:vNGl7F3/iKzIoiv2uYXPbG9I7V63waheCNtCq5m/rDk=,tag:FYLWV5z6uRcqEXmbzNUeoQ==,type:str]
    password: ENC[AES256_GCM,data:W6tqHEDdkHctcRfk,iv:aiCg2P+OxAchk9VE5jkmxAcybWziHt6RPeLOl92argQ=,tag:HjEE4WWx09ZZhFiFYc0pvQ==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWmU0eEtjb0hDb1hJTDF2
            Y1BTSmx3RkM0ZjJ2RE5FdkRPNzBod052QUVVCjdENmE1UmFoUEgrSVVPbUlhd3dv
            dC82OHRweE1PcDlaQmhYRzJvenNJdlUKLS0tIHd1MlZwc2dXaHBkVnZudytJbkEv
            dUttL1FVOC9kbkttWGlab1FBUGovb2sKh+qNjGYpYvv2si3Oqw6hOp9bWGKe4LS7
            9xQRqGWyA0O3YI176WgKvQishllxNKC/lPGxMn/rJ6LvL5L78z/mKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T20:52:31Z"
    mac: ENC[AES256_GCM,data:fwRENsQ29QmKZSzCpcNfy9HPjEBGEVezBOq5mcgYS4azidSSgi/o9fcp/KlubxL8G9JMUn3PAwuc4Xma3xwTOVYwL0juAtHjPTAaenKXIRmVvJC9yoKBoUMjT/mDOAU9eyMXicdZxxQvaCGNga2XZ+nwrFZRckyevG/a/LSDlDw=,iv:1uScBScUyFy5Inr18Knmnw2KLRHTTZ/bLZOuAIIdTHQ=,tag:LFYlJGy1kIDIlW90Plk/bg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
