apiVersion: ENC[AES256_GCM,data:A+4=,iv:nsOWpZb2YoLdI/px31bDL+t2Xa4gSE8ThSwLxDjsfCU=,tag:pk6XHFGtmBx78qY7QERBfA==,type:str]
kind: ENC[AES256_GCM,data:swGJBVjS,iv:puSmwuUHK9mYrFAy8CqTpDQGxn+SckXc9fhSCECJNL8=,tag:bkELY0bswmaXBJXACmEX0Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UpBEW+LGjh0rb9vSCS63WtZJ,iv:0kNpNdqpjGgOR9i8gbpnbTwRvWfhtNPEGMqBJFqw1g0=,tag:bK08l4NKyFcqZQpHIZ5SoA==,type:str]
    namespace: ENC[AES256_GCM,data:x3d8ezVOEcfjoA==,iv:lRXQPAWmgzXOpDM4JFCaS2A2P7XgvL2QU32PNj1WSq8=,tag:b8FxQRNzi5yPFYL3X58J8w==,type:str]
type: ENC[AES256_GCM,data:oEJp6LsRsiCrbL3HoakPssHPAXgEvdvf,iv:s0bnQp12vFhDPNMlCq1h9cV6JHLOxoJl3DPABGSgGiw=,tag:fnXWXVqzC3VLiJEMYzWkyw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:inoD,iv:JPQR6Nly16jYTrMv2y/GbmQ1ZYpwqHC4fBpg1DqQ+Fg=,tag:ZV0eCCvqD8qmqjTMrPi+8w==,type:str]
    password: ENC[AES256_GCM,data:stlWBSN1pXx9YJU2,iv:RlQ5Zz6z0RlIFrxKEVzcZlWDzdX3nw0Rz+K7kVgUTV4=,tag:BNannvf3dcedad7oETWJAA==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VFRnc2xxUFhlV3N5eVh2
            bGNMMEJrYXBMeTJSRmdkQ0xWVnBxTy9HSUNVClBybnh1Q2FqbHc3OGNrWWJ5RHpE
            RC82MDdLT0NWMmxMdE9Sc3RESUJncVkKLS0tIEZPWmlQL1NicWxxTkRLT0xjOGlo
            M09jMldyVWFhMFNWZDg1cjlTMm1EbTAKgVy7fZQQKb66N93MEy6EfeicnSL6U3Qp
            hSxxoa/703K6k41YBOYiN4nRylJfIRABM+ERn7wqrBG++MJY5MiS+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T16:42:53Z"
    mac: ENC[AES256_GCM,data:wCBovvvJcUOsDvfjcmXMntsTUfOV9tApX8uxJHWcGS5qpxKthahzhxpaWiFBITgxCQ+ts3gh9mAGtKz+w1LneXEbhesN9pMdLZDFmVcFLdupVaBAnabyVBhv04bLarkWZt/GBmsahNqBRJDt22s9+T+ga5Sbmc0iWjWJs958u/Y=,iv:9zOiO8Jt/DtrwYMZzl3IW4bdYYrZvJ9UEvYzXyi++kk=,tag:4tLqJwvaVQEKtyxHOPNyzQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
