apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    app.kubernetes.io/part-of: apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: networking
  labels:
    app.kubernetes.io/part-of: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    app.kubernetes.io/part-of: apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: automation
  labels:
    app.kubernetes.io/part-of: apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai
  labels:
    app.kubernetes.io/part-of: apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/part-of: infrastructure
