apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-prometheus-stack
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  version: 82.18.0
  targetNamespace: observability
  createNamespace: false
  timeout: 15m
  valuesContent: |-
    grafana:
      service:
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - grafana.saradomin.ftm.dev.br
          - grafana.saradomin
      persistence:
        enabled: true
        storageClassName: local-path
        size: 5Gi
      adminPassword: changeme # replace before deploying
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

    prometheus:
      prometheusSpec:
        retention: 15d
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi

    alertmanager:
      enabled: false

    prometheus-node-exporter:
      extraArgs:
        - --collector.rapl
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
      containerSecurityContext:
        readOnlyRootFilesystem: true
