apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmchart.yaml
  - loki.yaml
  - alloy.yaml
  - power-dashboard.yaml
  - logs-dashboard.yaml
  - log-volume-dashboard.yaml
