{
 "title": "Kubernetes Log Volume",
 "tags": [
  "logs",
  "loki",
  "kubernetes",
  "capacity"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "loki" },
   { "name": "cluster", "query": "label_values(cluster)" },
   { "name": "level", "query": "label_values(level)" },
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "pod",
    "query": "label_values(pod, namespace=~\"$namespace\")"
   },
   {
    "name": "container",
    "query": "label_values(container, namespace=~\"$namespace\", pod=~\"$pod\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "logs/sec" } },
   "targets": [
    {
     "expr": "sum(rate({cluster=~\"$cluster\", level=~\"$level\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} [$__rate_interval]))",
     "legendFormat": "all logs"
    },
    {
     "expr": "sum(rate({cluster=~\"$cluster\", level=~\"$level\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} |~ \"(?i)error|fatal|panic\" [$__rate_interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Current Error Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "logs/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({cluster=~\"$cluster\", level=~\"$level\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} |~ \"(?i)error|fatal|panic\" [$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Top Namespaces by Log Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (namespace) (count_over_time({cluster=~\"$cluster\", level=~\"$level\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} [$__range])))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Noisiest Containers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(20, sum by (namespace, pod, container) (count_over_time({cluster=~\"$cluster\", level=~\"$level\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} [$__range])))",
     "legendFormat": "{{namespace}} / {{pod}} / {{container}}"
    }
   ]
  }
 ]
}