apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: v1.21.2
  targetNamespace: cert-manager
  createNamespace: false
  timeout: 10m
  valuesContent: |-
    crds:
      enabled: true
      keep: true

    prometheus:
      enabled: false

    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        memory: 128Mi

    webhook:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 64Mi

    cainjector:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 128Mi

    startupapicheck:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 64Mi
