apiVersion: ENC[AES256_GCM,data:cLY=,iv:K07QRNixtaoN3VIjoy4ZEDtqztLOuRx5c3FTgJItnYI=,tag:bbSqDB5kpmZa30z7Zc0kkQ==,type:str]
kind: ENC[AES256_GCM,data:VM2Js3f2,iv:VukBw1toDppCzE6Y7cSrL1/Ll9eeacl1l9U62m//7gQ=,tag:q6x6X7OuTX3OxW8aVyZ0hA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bF8A0OwERIWMcFevTtXZ4F71AJM=,iv:Cyq3JUIMIyO87lgLBeYTYhyj4F3xxFnJTfXHuLSPF70=,tag:NTWR4/v8AXu3xHX5io7gTA==,type:str]
    namespace: ENC[AES256_GCM,data:vavF1ZWBc2myzjN3,iv:syZ1iojAukoRSgzL2FENJxbThaeYDlz9pm5NbyBEtD4=,tag:mZHhFVWb8nBEfddY7eeKSg==,type:str]
type: ENC[AES256_GCM,data:QJrNHSL6,iv:TVsH9TRo5e7ceB/vwZD6HmlUnQt9O8qpAM1HxgGxxRs=,tag:LntxUlYUh7W7ia+wuXWiEw==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:OfEyalWMHto5vmlVp5wVdUrdlJLDDuTujFB+VW1vVEdYG3n7vV1Qf48jSiTWB7th+0NDLZ0=,iv:LBHrcpsHSwUL6xTAhvAKTmR8UQ4NpjOFj8JPQnthm7U=,tag:2kMDF2/xNoJelaYMmk0JAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMXBFZ3VkVi8xQUoxL0ph
            NWRuTWNrNE04eTU5dW1QR3dFUTNGWnJIWGxrCmFZaVhPVzhMTFJtZWVmdG1pc1Rn
            WUxia3B1Qy9TUUlLR1d3RkhnNHk5bnMKLS0tIFJVSzhjTFBWZ3hKNEhoVkpTODVC
            c0FiWmNOemE0TXJ2SWRycXQ3NkdObTAKdy05WfHf3b3i8Og8+px/LBFx4eZ/BFDa
            /pbZqVKnkJ4BDt/4M3PvD+hiJYpIQpUvLf9/qJHeXNBeR8kPDPrdqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
    lastmodified: "2026-09-19T22:13:47Z"
    mac: ENC[AES256_GCM,data:Qxxfr8AZ9gHDPruI24h41jw4sDVbO+ZoqsygvMnpd4EWjDX1ojOu0Hg2qP+b3CEhcxSohtKQZrE+NBivhzB385opWnI2e1c8RWpRn2/53NvR/0jLXdJWtkMRUIi/lZVjfUNVSVNTbhUJgCq3/eMeXAOkhaFZNiSDUIX2p6gmnZg=,iv:+preivlpPdZyo6azmW1Nsc9phsJhMWxGLT7eB/xKspQ=,tag:KVB9hZidHstkK1/teCZIfw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
