apiVersion: ENC[AES256_GCM,data:qHE=,iv:IE34pq3IDum7Uykkstmw0WyoMaEQwtqSNGZ6DFf+SdE=,tag:KyeBBUH0h3np6t6ZO8CRCg==,type:str]
kind: ENC[AES256_GCM,data:l0Xpt1HZ,iv:czp2gJJN20axP2BXRhJwSOy6XNYunVaBN/HDsj7aLWo=,tag:H1nx9fV6zXunAcqrFQuHAQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eHXo83/3C/9Nbif400OE5qefdafE,iv:Wu0F/fqnzOZ3cpcrHsx495BxaMWAMSKiXc70kfUZL0c=,tag:aEPv5AAGvgaRgIli9+Ww4Q==,type:str]
    namespace: ENC[AES256_GCM,data:Cc7EEwjkhOYg,iv:wKoJqhI/ubWPyPdNyH987AHrb9OMP9n6gw7FSpxqQgU=,tag:3YAQ/OlbncbVscTpB5moQQ==,type:str]
type: ENC[AES256_GCM,data:PYGtIB19YB750KPzGL3bdk42CA5eYja6,iv:Ydk9Er2MmdJLT71D1e98CXxBNu9984OgZBc1pCDBabo=,tag:Y21uynEnOATVHbBz6FUDlA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:8fuIDHbgKTzyByg=,iv:V5HxoNkJAwREfl5zIdvpNN6WDY+MrxcYk+MQRXIUWKU=,tag:2zuMTss8C/ODgtzpDYXK9g==,type:str]
    password: ENC[AES256_GCM,data:IUxl+QpTH+hHLnAg,iv:T4ZCKe4Q4CPcxONZGFaTDek2paS0znAQiO3b3Y+r8d8=,tag:0SSi7ArXgO8SteowiumQLw==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYkYrUDVzT2x6dFl4MkMy
            S1QwTkFMMndBdmFEaVdqM0JuOEdTWEFRSXhzCmVWdklUNmpUNTRYU3pHNFNIYkY1
            TGJadnllWFNjYVdXQmZFZ0ZJWFRKMFEKLS0tIFpRaGh2cnd3ZkpiMW0va3FLdUZ1
            UGQ4Y1FPcHpGRUQwdHp3SEFONUI2WGcK7H30bHzfdJPc+cp+ZOc7/qk+cg2M3Vbl
            o17l4bra5PxsiqDakjq2f9EGgtuThZOIYH1Q4o2fyos5VPK6/i2CEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T16:42:53Z"
    mac: ENC[AES256_GCM,data:Oxf9Pe9MHFicsj8L0yqBv2qPjQkCEKP6/BvViNxw+8UX+P1+qXObSGAMjUwP4n/V3C/RR2/e6iUUgKhwB2wV57uF7QxL9l5FlzZCX1kC5W8mQITroCKw2dkNUBbnqhdtNJx09GM8D1jLsX2XTgfwZXYdJZw3APj8GH8tSuzdXm0=,iv:hLRmDELPYC9prgtpOEzIW7DwVJiFyKS6y8SOeKtlGzw=,tag:36Jx/KGb5hih+eqTvvLiZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:w5Q=,iv:+M2/S7TH1YYqX+IOVjuE4Ye/UeElGggFoNh7mGKGkkg=,tag:yVG0cvYET0de9bTf6d7xDw==,type:str]
kind: ENC[AES256_GCM,data:hRMqEFlW,iv:MJklQvfKz2WtPscS43G+LrdjiNIKKmAhPC+SJ/Vln1E=,tag:/IKyfwFD+dY3BHWD89vgHg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VGq9kr7yEJc1E8/4ZA==,iv:3SjxHdvuMN1jg7kO+RPe1QDwK6mGGJJBR6cJT2ogoiM=,tag:/aGJqXetXNhXs1sa8mF2Xw==,type:str]
    namespace: ENC[AES256_GCM,data:l63gkSzYL9vh,iv:WiWc/MaMRG1uxfA1cpwW9GWP+Sk7LmNkzkJD1xDrtjo=,tag:0kgDKZpYSx8A3VQg/ku7ag==,type:str]
type: ENC[AES256_GCM,data:WTmz7YH9o8/D/VfeuUvBiKf55xKLflaT,iv:fie8DhTfqOl7lMOrhBo7GLNBr1PxeU1yQdfzyn2zNZo=,tag:bjoM6l1mGbl8PAfLeHu7Dg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:yKIH,iv:0z6ZKKo4WZxmlE1+sdEsX6nhe1sHOt8bjGZ7mtTMPXU=,tag:zQr+kupIYNsW5hB6SeMKwA==,type:str]
    password: ENC[AES256_GCM,data:MK1ghbuyIQlh636L,iv:q+jMPFoqo4GLPvFe1Q7qPgvmAVDxM6HdOZ1qZDvg9wQ=,tag:1vULVn0YZJGkaA5zmbDtgA==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYkYrUDVzT2x6dFl4MkMy
            S1QwTkFMMndBdmFEaVdqM0JuOEdTWEFRSXhzCmVWdklUNmpUNTRYU3pHNFNIYkY1
            TGJadnllWFNjYVdXQmZFZ0ZJWFRKMFEKLS0tIFpRaGh2cnd3ZkpiMW0va3FLdUZ1
            UGQ4Y1FPcHpGRUQwdHp3SEFONUI2WGcK7H30bHzfdJPc+cp+ZOc7/qk+cg2M3Vbl
            o17l4bra5PxsiqDakjq2f9EGgtuThZOIYH1Q4o2fyos5VPK6/i2CEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T16:42:53Z"
    mac: ENC[AES256_GCM,data:Oxf9Pe9MHFicsj8L0yqBv2qPjQkCEKP6/BvViNxw+8UX+P1+qXObSGAMjUwP4n/V3C/RR2/e6iUUgKhwB2wV57uF7QxL9l5FlzZCX1kC5W8mQITroCKw2dkNUBbnqhdtNJx09GM8D1jLsX2XTgfwZXYdJZw3APj8GH8tSuzdXm0=,iv:hLRmDELPYC9prgtpOEzIW7DwVJiFyKS6y8SOeKtlGzw=,tag:36Jx/KGb5hih+eqTvvLiZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
