apiVersion: ENC[AES256_GCM,data:Qas=,iv:2IeNSSaNX16eqIyNhkrgKDeHPBsbZ+JLW+WifRYoTL4=,tag:jDyJPBSY6OT6GASvtWSWRg==,type:str]
kind: ENC[AES256_GCM,data:6bpDF0QF,iv:H8Qemzt2nUzwOFXj3urOORid9a8luOXCTVYAiDUd0JE=,tag:8qWRgq0C0AGy3o0eBwTtNg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uNKuwgA9rAxgo1VIDB1K33u7,iv:uiFb/00x6KV/26SpwFxhxwUr6E+cZGCGrdSmNFfDyLw=,tag:Oq8KPuXLjZexXRsRUMe3bw==,type:str]
    namespace: ENC[AES256_GCM,data:QPu4tKUCeqQ=,iv:OQDwlTbLRiE+vuSRCJMVOPeYEXNn6Z3v0r8w1nwO1k4=,tag:Bz8KbUNX2puQ5ODCutmwEQ==,type:str]
type: ENC[AES256_GCM,data:v/64CFOC,iv:Q4MQXqbf7MWhQ4UtvDrl0izQgegBKY1un7Y6HDXctrM=,tag:m67IRLDKmsF7PXdXK37f5w==,type:str]
stringData:
    database_url: ENC[AES256_GCM,data:iKxbjNOC6gem1f4PytY8Vtx8QZ+w//oMtbG2T7zsa1EPbJF/SMt3NpsL7ZxUYHKbbnfaOZL78+Q4NUhXxJLa6ShPWKjXTP3Vb4D/AAhKmFPBGXASFY7JPgihMswGWg==,iv:NLhlYCI3b2f6RbiXxjFjxsYqKx4UQy9yKcyQZXPDmXw=,tag:Bze896hNkCdi8cTQVucOog==,type:str]
    admin_token: ENC[AES256_GCM,data:0vhdx5wmqeYTweD6BtPNOXLyVvoXxtdIVpcuqkmjf+yQZW/h0AU8uMGqXk8=,iv:2GRzbDsFjd3evetmXBZu2kcVeWd6y9dtWroWxMMFjRc=,tag:ifZ7ujQdU6LWva/z5+jkMw==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVDlPMDBNWmUwbS8wN21x
            VkRGcjRHSklkRmthc2RLUXE5QkZ1aUNDeFVnCjFEZ0xJVmViODB5YS8yZ0JNYW5J
            Zmc4ZTZBT1VEd01hVTVtME4wcFZVZzQKLS0tIGE3UEtIemwvMDlrT3R5ak9idmdS
            U3VYTk10Q2NKZnI1Ukx3YllDVzAwd1UKcStasz9yZa3pvOZj2+5vLUkO3B7JSUQM
            IFFZGf2his1GGJkS7DhotojWXkli21qXWuY71FkCS1Cxna4quX363g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T16:42:53Z"
    mac: ENC[AES256_GCM,data:Vl2sJUms9VYV2HXOLsSkKBLi8+YR/Kn13rdnSgM5YivH8bwQkm8Wk4EKWmqcTdcx1zvXJWEuevIc968Hwhs/WZBifFnYTt3n2et+c3kRW0PUx+k7yrpAe5T85SDnFbW9kzA1Gj2aeoaZieypMl8tGZJ8WrZncpH5bMH3povtlQ8=,iv:kQt2itXL61akln69i85jpO0Jk0bYvVw5Q6l+SmH9GSw=,tag:gMmaGIC4ExhmMVCUMt1l5Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
