apiVersion: ENC[AES256_GCM,data:33Y=,iv:WlCK2WFXhAT3EuOalvAb7OvJsmFs1lVfDR2mIeY88hw=,tag:SnjgoAcMwdOYkLGDzab/UA==,type:str]
kind: ENC[AES256_GCM,data:lfA6PK4o,iv:Q+l75lWPhHgd/ipH/dnJFgKvuj1SRmuvKMeeCQEIsTY=,tag:LlUCIfFv8cCgRTUJDoSmWA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:l5D6NRN6Hki2h48JZ8j/JA==,iv:OWLUWK+rWMxdmMrter/sNq7CK5fA0YoakrEV3f9mgaI=,tag:UIRWl2SxfcVmm5ITvGkylA==,type:str]
    namespace: ENC[AES256_GCM,data:q/EfcCE=,iv:lPEp5Yf/oqnGNCrHoPW1Ny4rILpcFAgt4r8svMdnwFM=,tag:r2ZFrbZWCDSpejFifnbOnA==,type:str]
type: ENC[AES256_GCM,data:GgotvEai,iv:OkiaLsgaBlrYTbOoX/nusBPvZhZBbcw2UOmtjFKUIYg=,tag:Ecair48obqsWpNeKU26hFA==,type:str]
stringData:
    USER_ADMIN_NAME: ENC[AES256_GCM,data:NYg2+qk=,iv:kLRRt9+f/1Rs071rDK3+Dz/TM7wpv/aahP7dfn6K16M=,tag:qz8JeoEflVRdjWKukS1LZQ==,type:str]
    USER_ADMIN_PASSWORD: ENC[AES256_GCM,data:Pw5r2tPxRqyqydpnf8PXGJkRWkZO80wcq0+58pNoT/pDO2vta57EfLZBXfSPr36RgbFvOI1I8+1DlEXYjz2Wrg==,iv:XDsgUBcaT/7hUXLYv+tGJKOrr55/7oPhWvbKMV3wVvM=,tag:2gDr+I6KB0GNdx4zOOjP+g==,type:str]
    AEROFOIL_SECRET_KEY: ENC[AES256_GCM,data:k78PeuFVd+HnH1CoaPKamLTp3mhYPtUODcqblFDkZBQWfC1rLZ4Js9B8hzP3GmXZYt8T06TQBg7zAWZgKEpGYA==,iv:ea/whWQTJSPZ6dkM00OwDBJju85IUHxZl7c0eEbOufk=,tag:voaZWcgO3C3R4OjQcAteug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VmdFeTI2MFNvS3J2ZEZm
            UDZvbjRlaDB3U21rOFNyeFd2ZEhSOVpXalJJCkw3bXBqaEUyY01wc2JrTWZQMjVN
            TGhFRnozMlRWTllGN0VZcW5Cb2xYK2sKLS0tIG9yYTJ3WEF0d1RQOVd6elpkcnJt
            VHlZV0Joajc1YXNWSmsyRmtWYlh6bFkKe8ph82g374UGS6XCX/XXj4GHeauBHgO9
            atMG7bQobqXfoGaB2alCtRQ6/auCizIqsADIQYmTWFp0mdBViTos2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
    lastmodified: "2026-09-19T14:38:13Z"
    mac: ENC[AES256_GCM,data:rofBS08oT98i43XRsPNEVVhvETjZvfC3fc4VTJfCHU5djYxhIvRpcGDqT+Oq/axmij1Aeo6276xuw0sTCN21MuPlFGtJv9H9Ge3jktPNPiZjdmWNQ4px/KBqUMAci4tP/OdstioHc0pSZy/yPUh1XWiCHXEgLQBzYjr5lQsfK8A=,iv:40LDbCJqUwsmldU1qThyEZl+7+gYfXr8MG7FptY/9P8=,tag:UAEY5fJa+ESHxYEOvq7QAw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
