apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data
  labels:
    app.kubernetes.io/name: filebrowser
    app.kubernetes.io/part-of: file-management
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
