apiVersion: ENC[AES256_GCM,data:aWQ=,iv:BXZRNizw5cHJP/YWedgnQyaIR5kf6VYCz7VVdXITgwY=,tag:WvPnRNY9zYmYJGUGzk3n4g==,type:str]
kind: ENC[AES256_GCM,data:YU2STFQL,iv:YHsJ0JJBx+rvidz5qRYkK3l5cyRCpWSFhQVxojP2dRo=,tag:ogCXclVLY0YtWol02+Od1A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RwkSlFtxfKgv8yCCz+UQqQwziA==,iv:6FtzSgVfXTTNpBIq4A9ETK867WmVJLb9sRhHcuDGMFQ=,tag:zXXWpk/ntCdE6HcBYPQlHg==,type:str]
type: ENC[AES256_GCM,data:CPTQJGFu,iv:ItJCA6AeI1a2xMgKrtgRasEchA39KhSpKC26zfXofpk=,tag:m8EUOJCLA1HqBdZYqEz+cw==,type:str]
stringData:
    FILEBROWSER_ADMIN_PASSWORD: ENC[AES256_GCM,data:OFrsdxjATEtVPSG4ifuQCBmizEfi0XcDsgUCoXKTNu5aytmxbs5U8/wKQV+Vrmb+lxoRZHgYIrwK4bYQ3TUAIw==,iv:GT8UGK9uv8qssTrFUlRugGbZQvJNAzQLkmVLjnp1mwc=,tag:9ijljcOS7605vMCYjyIV6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NEYvODdZV1B6c015bjNx
            YXo1clQrVEdudC9MWHR3QjJFZ1RpQ090UWtnCit1NzhFK0laZ2R4SEJXcXlwV2Uy
            N1JidFhDQ2xyWDVxT0RYUmZlMDI1bWsKLS0tICtUUDczTVdrU3Yyb3FvTlh5MmhV
            K05ybUwxWGFBNGp3eTNXSmpVaWtoSzAKuxl7BAt6qd3lNL8rvOPO+FYYQHBOUdG/
            7TgibKerNrmq5BC8a6thEmSvqWKT6v4XkMUsGdVMf8xCY8hMGyo31g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
    lastmodified: "2026-09-22T17:49:47Z"
    mac: ENC[AES256_GCM,data:95bPHW27fMEu0CxPYuCP5Ua7WF0p3i7U0YPXISoIUGfoZT8kGJeYDcE1xs/BUJE6/5ulwYyqTZhlJWVE2OzIeCuq2Ij52XqDTC8I6FvefmPu2mFV0yXi6bvlLLaZXsdc934hENyV1px3f8wnQ5R/xTA2DAqL1x9HtjFozAmcjYw=,iv:EK/cI9qvjQSFNZcz5jnLAIAgUG26jvYpLmwH/KhxZK0=,tag://21uQdgPcUMkN4p3MchJg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
