apiVersion: ENC[AES256_GCM,data:RD0=,iv:v1sk0Ojwocun9SlQbvfwjRpngfpZL4He2Nom0OUi7Ng=,tag:VA70dEQ0ihvrewSZ+CyFoA==,type:str]
kind: ENC[AES256_GCM,data:xDJ55+Z4,iv:2ICT6Ap8C60p5MzZNtlrUdtAn5yrLV2cRqEio32CDms=,tag:X+0u6q7ttWjmPH/Q3J8zAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3HvmoiCO2PjrQnE07KWcGA==,iv:1t9+T/iCMR/X8MEaURg2TB8iAbRAtkSdj5th2BhFJYU=,tag:1Fhsxa0ags4ch9OytKtsKA==,type:str]
    namespace: ENC[AES256_GCM,data:2KU=,iv:vu1O1iU4C4u4Wjct9E0G9EVQuXul6S/tKZsLQSl5X6Y=,tag:3I6x232xwqYTOHEHHH1P6Q==,type:str]
type: ENC[AES256_GCM,data:+gN3EwDQ,iv:lHTMBlyr64xX6ISdHlxClH0fxzMufgMCvRrQZ1ayVDU=,tag:gI1BzEuJ/50Canvon5pslQ==,type:str]
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:SBXc4PIOvYmwMaltc+e0qPrKyplOUqKGLq/yU+c3xqzfEPD02f6I8YUhS8WMMOk/e6FbrlhiNX//wbfqhDjDnQ==,iv:pJuvYhX1P1ccxXb/NjJVuoFn0spz9Gzic7N4Be0app8=,tag:EynCnLvBnyfmLL8cwAmh9A==,type:str]
    OPENCODE_API_KEY: ENC[AES256_GCM,data:O+97ude6p7CuVf0wfKqNoVqL/U6f8/HEEX2f8Gh98NMg23CqaAQbOD5SGwq6/q9Sc+m8XRyPu0mwpRbOMMWNyN330Q==,iv:pBMYEtGzn3qE7yov/fYdv/X6DTtBmkZ4clhMZWdxBwo=,tag:688Za+8n7SYYgMHz/Hxtxg==,type:str]
    ANTHROPIC_API_KEY: ""
    OPENAI_API_KEY: ""
    GEMINI_API_KEY: ""
    OPENROUTER_API_KEY: ""
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WWJEb1U1b2Qxck5SRGJ3
            RUVLS0tCYzFmdEczcHFOa1BOaUh2UGJ6MlZRCkFmQktrczhLOXVpNlkyT0RZVlJy
            QkxucmswR1ZaTTc0ZzdXTjQvQWYyL2cKLS0tIHNGNlE4TzJsOWQzTkYyUlhObkZr
            MzZNbndVS29zVndQVlFPZUpKa1R6b1EK7Ce+c+ivKNuGAUwhk72QS1XlTfV9euuT
            ZrkK3TWxVzX28A4kelW8LSIAHd/mDfNUXaAYmCQt2u5emOChtcR2/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T16:42:53Z"
    mac: ENC[AES256_GCM,data:0nJoxmxP2dTfLjKXRoypkb9VCWbMmr+l+bAvZBEyq390cbAL3MDp3WiDMKBLDzHzLR/B4G0hfk6zu2+9PqZ3tebI4GcsxJZNk6t5jnW6f2xIMTEth+1KZlzEpvr1mZKVdaZX2pl1BVSd33A944ZeFGcjQoiRy6VXfuh73sPFDqI=,iv:VxNwG+m+BnqJX9nqQu+V2XUO8VM6cpBA4heV88mLWbw=,tag:AZ6/hRycjGxh0fESfraqrQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
