apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: values.yaml
    target:
      group: helm.cattle.io
      version: v1
      kind: HelmChart
      name: traefik
      namespace: kube-system
