apiVersion: ENC[AES256_GCM,data:Frw=,iv:qFYoRXcIydt9pe+e/STvhvwKn199kLVBH3C/0rVoqlE=,tag:GNgLxPsmINMv9c0G6d3IuQ==,type:str]
kind: ENC[AES256_GCM,data:VJHgXgcz,iv:e37EfakFo7+hVOZM4yp8ciivvroQOAeI9Eco0r0kyIM=,tag:WiDPjv2joconS1eYsMnZzA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ym1wHef+92khEwhpD2iJCrHk,iv:3UqLum7HgsKplejvid9//NX5ywB9IChAwNO5Rqs1ifo=,tag:F84+Cuq6O1vcpFi5lsPLUg==,type:str]
    namespace: ENC[AES256_GCM,data:ZPz8TQO4cSk=,iv:1TpXAoV53cSs5KFNDxuOoQiZoUsXXYheGUcvunA4eU0=,tag:3VpQtpVotxLwezm96Yhf1A==,type:str]
type: ENC[AES256_GCM,data:uD4OiE/l,iv:Ny3bXaGcffVNft43kKMn1QJ5jH8WqlMBWenPMSzGuA0=,tag:ICtHo48X0eFrcDI/xBjadg==,type:str]
stringData:
    database_url: ENC[AES256_GCM,data:aEIrtGIB0+MT9BHWGQ4r/qKRnGQzK/Y8L8WXsIhFc6dXJ+2DlXkx/hEWXPEJUXpa9WGWHfjUB+PcquCRpgaHzKRJ5zxcRzd1sssv7M3ouBBB/DayQeZi8ijCk6jkZQ==,iv:TAJlGmg2wVgrWaR68sFG98/lI+AUcPOCGPnLiNHUT70=,tag:RgUoTeIBddUQmTSOItuuFA==,type:str]
    admin_token: ENC[AES256_GCM,data:T80Le8iko4TjJo95VK6KP8eeCF+5P9dK5hykUfwU7B+kLYURd614KFi6Meo=,iv:HGYs7a0CPb1lEgoCAguyBKIwyFBcqnGYtRerY6EGCxg=,tag:SWJBZJJUSsRWPv9BQNR6tg==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6c1FKZ3RIZTd0ZDZBdVk2
            WmNpa25YSzh2SGk3b3cyejFtTC9MOUhpVjFjCjdSbXRmWkpZQWpJdHRWNFBPZEhW
            QTJRQ2k4NEdVeGlWMS95S2ZvZFRBVGMKLS0tIC9IdENPbmgrWVVGM0hHTkNjNXZ4
            elU2UWowam1TdWVRU3pxOFg4MVpwOFEKZ+sNJf5MX2PLiv9l3kSf/47QbAjAumdI
            2jAoV299ojwQQ2DCJ5viBeXj8UUaEKEygyrPKqKinbie9NeUPEr5vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T02:34:38Z"
    mac: ENC[AES256_GCM,data:81qjDPmoh3IOlsg87ujxcZDhs0OpvSKXnBLdCKLYbx418tE0iXqwGEsFRM3TW7pp2UhvPSs2nue0wzvRGQgv5GTlXMzag8fbTmZ1TqgC8TWr6/Bm/pzOw+R7FI35NotayhgYCk6DqaEwIL0YVlPOKmrcb/8bDS5jCARiR+Wg2NE=,iv:862JFx4mUmPmZ7XKSfyhhr7COKrYeM3ZlvIV5ciiet4=,tag:KHX8GNzk+F2Bp8BvVGZYNg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
