apiVersion: ENC[AES256_GCM,data:+uE=,iv:yR1guSGOUZKagk68ceHW6EpOFhKRfkN37Yp8WO5Y1NA=,tag:yWcQvFIaqrRvnn1CeGrdUQ==,type:str]
kind: ENC[AES256_GCM,data:q6p77gKn,iv:V37lilqm1OP3AmSu0Nw8PsIO0C04mPaBqt9q9/T5ruQ=,tag:joHzFubfY0Td4L3/7ABe0w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mh/BzX4xz32PQoR5p2HjyKGc,iv:D6ipu2zHOWgOd1lUmBF6CJhQCuhB0ePjduy87kuzT3U=,tag:bbRlgjTNCYZEKd5GkGRXtA==,type:str]
    namespace: ENC[AES256_GCM,data:d9SRut8zXpw=,iv:AIEH6gSdtw6iv1x7jbrltPYxGWlavYbPHx7hRIpnj8o=,tag:TYELYe1tmt4r0jHxtqlLNQ==,type:str]
type: ENC[AES256_GCM,data:TxLleNr8,iv:idAtwTqBErmw5w+6t55Noamq0Od4w1ot57O+Wwp4H8A=,tag:S+EveFE+LqqBliuA3SCp+Q==,type:str]
stringData:
    database_url: ENC[AES256_GCM,data:Be5/d6PHWgNziSLwz99s3uybrlf6ptq3hRQaFMsRve9HSvuoKqJUb5fPTWL2E00EHRSaqkNSpdJE7xlYqeTLDrEvJy730nKeIRo7fiEQ0DCh+TZeC4KO1Up5gP/ODg==,iv:3dJObIozzNq9mDTH1XJbftP3lQS6uUK6RcGdCNGtHfc=,tag:Wx+2Ox6pGmOVvkMXHqIKKg==,type:str]
    admin_token: ENC[AES256_GCM,data:t2A5qkzVIZEtLDk502u3X47U3gCytgYkWoXRAiB2gK+gFLBPDtn2KC4B9so=,iv:acciAcOI+WJbkUGtGNm4LWMcSC0AVfI6qZlzeKceTDU=,tag:Tyh9l+1m54lxIkB3PuU92A==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YUN5b2x5cENneWRWRHdv
            V3EraFFGSExLSXRxWWg3OWFtQmRlWlppQWdrCk4ybzQ0VUt6K2IzNXV6cHZNbTQ1
            bS9sN2hMOS9peG5hTUVJMUxDMy9rZFUKLS0tICtOSFR2QWNNUEZ5Rno5RUpCaXF5
            U0VOczNSZVdBSnFQazVpNEVIMXFzOEkKIKdBou63dM9ckfRD1MvX9IiwgdAImrkA
            S13EZE7dGS+B053D4eVBIGcDgnDSj6Z+0GWqs9jZ7fUe7Ab/Rthr1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T03:10:21Z"
    mac: ENC[AES256_GCM,data:KkEEGaaZtYnDENjqZQg9FapL9O6FriX53Mup8VqHavQvHcb2E5MAE94D4ujQQROeU8bYg5kPl41zRYsJd6VnTNB2VSWwED4yZnpGBDnC/O/7ua9yyqGRD0BIkBwm6sIaFYgvTpw90Tm/1NAHq0FdfqM9sWj0OvaaKic6qyo89tI=,iv:Bjhf/l/D+xgULQ2vlGg2yKdAS+hP0K+7XM4MguSafEw=,tag:tGY0M8RZSXd7NykFyxOtVw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
