apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - buildarr-config.yaml
  - buildarr.yaml
  - recyclarr.yaml
  - qbittorrent.yaml
  - prowlarr.yaml
  - sonarr.yaml
  - radarr.yaml
  - bazarr.yaml
  - flaresolverr.yaml
  - jellyfin.yaml
  - seerr.yaml

configMapGenerator:
  - name: bazarr-profile-sync
    files:
      - bazarr-profile-sync.py
      - bazarr-profile.json
    options:
      disableNameSuffixHash: true

generators:
  - ksops.yaml
