apiVersion: ENC[AES256_GCM,data:g+Y=,iv:TMDdBgA3qpgsPbfqGnxtwTG4tBMT+z+W4y6h7J2jBkc=,tag:PaDNqYbSXwfJYADab/h9FQ==,type:str]
kind: ENC[AES256_GCM,data:yBnlXefS,iv:LTvUBjlgGNBLEkxs2IDkyi5JngDUM72l/L/oj+u7rMc=,tag:o1Vy3RNgnnPc5IbV+y5zQg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IbHvkRT0w/P2FaB6,iv:IW6A1hoc9Gi3EnzQo8K09rERXZgON/jh/DVbhxryMls=,tag:PJ4DcKxF6uqSmiBMgxkLCw==,type:str]
    namespace: ENC[AES256_GCM,data:WSHl51M=,iv:J6GNWUIucecZVegGpgdfcaHZiXhQyDtVO6x6fOxU5/Y=,tag:r5fZdlejuj3ZOQgqPFjMig==,type:str]
type: ENC[AES256_GCM,data:f2x3ZEOb,iv:F2bFh2wE52C9UwmQ1YU4z2vtNMP5UbkZFjDdyS8d7FM=,tag:LSlDiXbRFM7XDfZora+bSQ==,type:str]
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:rA0V35SjLX3Iqx2dQQSLj2u4NM1Awdu2GTrt/TC+tlg=,iv:ZA/f50YwIuAPQO8149YMEZGX63cu6bzYmwdGJXmlTr0=,tag:/1OhqmOAU7a6p0wNJnDALg==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:z2E1WJ7W0kVYxseQMmOLr9UIfSlbuzX1phhVKYF77lE=,iv:Ystb7rvMFkj9NqSmCOKGgEdkcJDQ4g3YXiFg3c6J4aY=,tag:Nc6iwJsyePX0Edfhs1Uf0w==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:AwEUeS3pMjOQMnYnmAr99venmX3Eu1DACe3M/41f9SE=,iv:1u53rjxcJwmhdeLQII6hbbwj5FXdsCCrc7xfErIBuPU=,tag:7wwjx69jw5wC2X1W3atE6w==,type:str]
data:
    buildarr-secret.yml: ENC[AES256_GCM,data:WkJOj/Gw3oKJGu4RFL1Wx44mY+4uEuc5DXl48UMwsTHzLdcs2y+d/KcYpTfrsdXCJkFdJ0xaZ56XtSVSNBdyc1U+Wz028eg9BDj0H83MEWeWjTAbs9GBCXJB/O2nqmeZWITTFz/m5BZMXxdcfAP9z96JDiwBaNljisCpQCVGqQeTchGfWN6hLU+LAgsAanX6KRWRvRLUvYV0e9ujLi1q+OkI5+t71EvyOOJGFqTjDjyLidFVXQKgK0d8FRzPCefWVXA03ZJRm8Sm2AGIQzKjYaGC576h3dFVXL2bjne9EYVr/kl0DNQVZPqmc4SESN8e2VvBk6JWKdTpjdj4Yv8PJn8W+wOJp5kViNXzxDgMZexUjHC2xB+vEj6bS9qlj6xqqArdpwfSJwXaRQsfbStyvnk4J1V06+OF02GZhXTeLPJD994ridPafg==,iv:HFOJbV9U+gEDTlvPPhjfrfTXZPGpCyN3CYjnptfHhLk=,tag:2bJSPwnYhgjWoIk77VvPAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFajB3bHdkYzZTdjZMOHBS
            a2t3LzhVWDNnYWpVYTJMNzFZN2FiZGVaVGhJCitoYnVxSU1aaFhrb3VGTHJwV3lX
            U2JScGNCNGtvTUN4Y0RhRmdkeTZEcU0KLS0tIHZPOWpYYkpxZ3Z6dGxkdC9IZVB5
            OU5iVjdHUHpsWFlqbi9kSTNzVG1uS1EKQFHjzqYVI11j78GoiwU8kHrZ9C4yOwcm
            7SOfK5IU5nnReBtWGs7AUl5ROL9tg/gqiFyCQe3OFKzREQlXlb8FMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
    lastmodified: "2026-09-20T15:58:55Z"
    mac: ENC[AES256_GCM,data:jKiNeYuk1hR+fTwd7RwU3RjWC1+tP70GNaO91zK3onRIgTjI2VhRs05dB1UqzldfrOFfnKqP1LvJ2LPjH5GqY2kjvmduHekCogQcFixU5Q+cpKVa/jDBCtYwknIP4X441U1SVo2v86Wt3yawWcdvG2yAzTRWiPwUoIUGiTWMPg8=,iv:pH45lv4OT6TUnmrGT2iZfqCDISDOTpsRA2U4KSAsQCo=,tag:KD+XByYSb+QEubRxdgPCWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
