apiVersion: ENC[AES256_GCM,data:IsU=,iv:FhnX84sZCCsmL0kE3JkZa9Z0Iqun38q6/aPehIHfCqU=,tag:+Gu4ewe7NbYRnh+YbXJKCg==,type:str]
kind: ENC[AES256_GCM,data:BCNLmKhr,iv:fCZCtxroTSuRZYohp6HGZvNhk57anu2MVAXgmeXUTbk=,tag:MeOUds0V0i/+iG2WHkAMUA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SM2tX1/zMzdYuT1/,iv:6Cb7h3wk/enirbWBy+0wm3Vd8R66OCyECuIsVwecGWM=,tag:xK9zCVy8ar2NtwVU9r4oeQ==,type:str]
    namespace: ENC[AES256_GCM,data:Avw4lMA=,iv:JmOf7Nuo6U+ux0q5y5IfN7NnrdlBG8itMdcwpQ9Bcjk=,tag:P4gcCGbQuIY42sDfUyEi3A==,type:str]
type: ENC[AES256_GCM,data:Kkoq7S8+,iv:WpQeVK2w1sN7Pvb6ywJ0yUnXDdnFrmwe6aY62cZA+tA=,tag:2pYxFtMNXWNzs2QB6EhdZg==,type:str]
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:/hVuUmbKBvRfkDAMie9s1t0rz3Dgi0e0bAQ11Gznqhc=,iv:ZujQY5H+TDkWSL/wJEedxwfNy5NYm10dbsFFkDfejWQ=,tag:1tpZ7eb1tFcXKRC6J7fy9A==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:/o2W5+U1zA0w3yuj/W/CXhux+G/KclnZ/8EPjSTEM/M=,iv:E+LIOaDngtqSAK4Q4UY0UFrUgmH0Ay4RFw/FpdoMwFU=,tag:PwGkxKL/4Sy+H6P/gUyDNw==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:cOfDsiqjTzzen/qS2kpMvrBZiIuEXrhIfBNKjALNQiQ=,iv:Ulny54nT/+2TI513kYfUXHhwJAJjhMMx6cMJtj7AoOk=,tag:LbobRXjPd6JELVMrqDmX1w==,type:str]
data:
    buildarr-secret.yml: ENC[AES256_GCM,data:z+Zv8ORIBeGLNCIDmPBFupNywvCkDqKVkX91uZtZ5O9l3KrKUOuSgbRkhiKLuNhlhj2oz+Pwx6XgDiz1TxDI6AXsgnCnnZ98EC2XqeS3Kz4A8tyd4W8oaOdW7JgvIlxlJmIZHM5j2DJ3HsXPrxTz1T4RPHtArS7dGZfswNPAwfzka/yIq3DBViePJpxCE7BpKb1U7UxzcyFwJUZjsHYq4vqp5VcAluX9MYq20IKHVyQojdmcucobKTljDHrwYoKPVrHrf/MRI5Md/IJI3qQrZJM3PkJMGdaZsI0Nw8+KAgJH3DsqX0vZ92huB/NUQt/+tTZtMx/IE51n7LD1W0d5iBmpiYWpjs8K8iKsX4xENfCG4SnlG4Ajcc5+N93lsGGC6BE+TEAtdzr7llzW8YNUZSFbLiSZYFB37tW1oPbIy/mQg98ENbpMqQ==,iv:5iOohbK3Npt5T8XlCbcPLkjBqAJTvhMnnitYiUFlBxE=,tag:mVcOvgpdRZItCCQKXx6X/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4T01jZUdYazNYbG9pSFpM
            VGR5L2I5cE5JMDFPNFN5SGZOKzB5S2hESzNrCjk2Q1VvL3B2VWVqaTdkb2VOdnpq
            Y1VaU0JiMkh2Sm1SZDBrSkFyYUlEKzgKLS0tIExXSGNoOUtvbzJoaXF4QzVGVHZZ
            OXMxMGZMd254MlBQSlB3eTVGVU1XL1kKeGKVhK1pc1GiQbxw1pBkUkTkKeQbjXty
            iZlwdb7iQboZ9882tgUAmWK1Me8hKv882c5TD3XfnF1vYA/otBeSCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
    lastmodified: "2026-09-22T21:09:32Z"
    mac: ENC[AES256_GCM,data:p+rBa/xOX6q3TOto3B/MDtO+Y9Z0E6APhzL1JrUVOc+HDPAD4mZk41IppRZZ0hB6skhYkoPIqvap+8essvQXWsjmXjBjTM4cGEw/crDG0lamA+f2L9vB5NwCOuDaWc5ynZv3egpFO/eqOEEd/iLxPPrJ+EGaCkU2KNkFfMfOgYk=,iv:QXqqSuwsxIKQGc2mUkvWDV4LQfxLI6quHIGAb2unuKQ=,tag:gRcWQYf1FKfd7HppKJxS4A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:uTQ=,iv:lTBRf5TdB7TY4fXCkH8bgD3i8oTLMj5W9gt3cw14te8=,tag:/jLQzpR+1To0NNh2E0LekA==,type:str]
kind: ENC[AES256_GCM,data:nwtEAWLF,iv:oKFDEzDLgqI8whEl/brcb7z/d7uu7v0WMp/iafdM2AY=,tag:ZZ8S9Yt9uWWXcz/7ttVDuQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:l2sdVCNl5m4JQtF8XVX3j1diL3O/5A==,iv:NQhWxdUREIquAhQRAutp/HH3ozXRAEn03j/aKn8uuzY=,tag:aC6saRgR/8wrNTZly20Lfw==,type:str]
type: ENC[AES256_GCM,data:nKj768bA,iv:72nMAt/EY/Epyy2B9UGSmgxdZp7kWMzEzIahCeh+Ptg=,tag:YWwJE8SmOtl1LggeFhh4GA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:MdvkwMs5,iv:9243/t0xdMBvymIqJN+VC6elmRnvDvScoXZpeKluOQE=,tag:HH9BD9e8jlWHbfgmgi/1SQ==,type:str]
    password: ENC[AES256_GCM,data:UaXeLMhR6SgsunEWyeyioZWmjAiNOK+H/wOdBIwMK7I=,iv:2MKY4NXL6DtOMUl4cvBsqgTyv0IpW7LtNpB6eyVjHLw=,tag:jEg6+Jed9LdlhSrvcGjzig==,type:str]
    users: ENC[AES256_GCM,data:sXrFpNrB2kZ2TkLNTnyU4hfOdU1JC9t2ji+FGNw9+ObzCc3R8fk4vvNLk77q/DcQHmqD7mI29/4oNkvjnI4qlirpgw==,iv:ImV96Sn1hut5GE2ZX5GDW2FVbaSiE6aaCm9LUOi5HE8=,tag:l1ZhPCEMQjl8p02DQjzb7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4T01jZUdYazNYbG9pSFpM
            VGR5L2I5cE5JMDFPNFN5SGZOKzB5S2hESzNrCjk2Q1VvL3B2VWVqaTdkb2VOdnpq
            Y1VaU0JiMkh2Sm1SZDBrSkFyYUlEKzgKLS0tIExXSGNoOUtvbzJoaXF4QzVGVHZZ
            OXMxMGZMd254MlBQSlB3eTVGVU1XL1kKeGKVhK1pc1GiQbxw1pBkUkTkKeQbjXty
            iZlwdb7iQboZ9882tgUAmWK1Me8hKv882c5TD3XfnF1vYA/otBeSCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
    lastmodified: "2026-09-22T21:09:32Z"
    mac: ENC[AES256_GCM,data:p+rBa/xOX6q3TOto3B/MDtO+Y9Z0E6APhzL1JrUVOc+HDPAD4mZk41IppRZZ0hB6skhYkoPIqvap+8essvQXWsjmXjBjTM4cGEw/crDG0lamA+f2L9vB5NwCOuDaWc5ynZv3egpFO/eqOEEd/iLxPPrJ+EGaCkU2KNkFfMfOgYk=,iv:QXqqSuwsxIKQGc2mUkvWDV4LQfxLI6quHIGAb2unuKQ=,tag:gRcWQYf1FKfd7HppKJxS4A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
