apiVersion: ENC[AES256_GCM,data:g+Y=,iv:TMDdBgA3qpgsPbfqGnxtwTG4tBMT+z+W4y6h7J2jBkc=,tag:PaDNqYbSXwfJYADab/h9FQ==,type:str]
kind: ENC[AES256_GCM,data:yBnlXefS,iv:LTvUBjlgGNBLEkxs2IDkyi5JngDUM72l/L/oj+u7rMc=,tag:o1Vy3RNgnnPc5IbV+y5zQg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IbHvkRT0w/P2FaB6,iv:IW6A1hoc9Gi3EnzQo8K09rERXZgON/jh/DVbhxryMls=,tag:PJ4DcKxF6uqSmiBMgxkLCw==,type:str]
    namespace: ENC[AES256_GCM,data:WSHl51M=,iv:J6GNWUIucecZVegGpgdfcaHZiXhQyDtVO6x6fOxU5/Y=,tag:r5fZdlejuj3ZOQgqPFjMig==,type:str]
type: ENC[AES256_GCM,data:f2x3ZEOb,iv:F2bFh2wE52C9UwmQ1YU4z2vtNMP5UbkZFjDdyS8d7FM=,tag:LSlDiXbRFM7XDfZora+bSQ==,type:str]
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:nJ8CVaWOGVynQ/KyxcdCtlG+PitWXTtwj26TmUSsU6vPsEKsf6cDgKlL3k2+6dMrzk330FtxRju7RmCd8GkHOg==,iv:7jtrRltBbzMY4mmCH5faNOY0MEap2c+aUmtnEIxJFbY=,tag:nJ5caUtUWOgqL0E9MeiV9Q==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:e0QFAQMHzUwgyvEIEsu7Aqqv+6HXQR9dsonbVP5EtYt8dDpKL407TpAd9IiLLXyKCQxDsV+T2xO+8ObooaZZWA==,iv:/bjglHbD4Ie0pSQr+8/yOi+VfkruwicfLJaH9pEBUpA=,tag:AKhAFMfCBBiaJYFDrKvRbw==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:qfDNn4JLVrVfK4bR2zOCyqwpNWFaC7+QpA+yUOd6LWQeDiMoZrYm5eCRTsZ6Rvs/BRULSSY54NoCuwQCIui0nA==,iv:NIk57olrzXGOLy+yLNK9qmnIQGa1eivcbxH4qoNiOzI=,tag:+GUeak1noume1iHumNqGLw==,type:str]
data:
    buildarr-secret.yml: ENC[AES256_GCM,data:k0760MHHfiF1T56oU92serPNmNSWlCnFdCX6dC9/GcmDywpd9B7jOgT88xpLxj/EFhyIBiHEbUY3mL2s/YpGwCbPsWZMF0LS08nD8G6FWWlnvh1G0LmLA10603eY6AYX7Y+xY5hhrs7Uvr60b7fCdTdt1CfOz9fZtrwQJFkXgiO1/XB7pwVnRh+PP37MjDrblxnQQfRy6TOHZKu63zLJWDoD7vjOsu2V+peb8sMEpLg1Whc36UcrC5rXB5o3YQaCIUVHHLKV8+MAqaPvciGokwT1SDLcPu9LsyRlJPWttIcFQR0jGHD5H7R21orxnYOqwAkVXIYjeE3Vsexp5hCOj0AE8z6LpaqcS9ygHMfFxoMfTRgaX6P1uFjHdbNpLdRmwlozM6nuooIBKmdq5yVFA0xr/DHVsoMh0JsxBc9c479yBaDKoeAVrGF03OriVyEFii6EOUTbPAvD0JhTbwtSv8EvQMF8AeF7Ph8VCz6WvM3cXCNjDrIlSlb73IuAjBtnejRrnjRuAq97J8UV86VHLPgmdbOVlKwlYL2/6SJC7gQX6CrxDuT3MZLTtr02Bl5dc+uE4w3OpjnstOZT0IwT7SaKUphewNvr,iv:8y1nRZsOcPbrIAhYk8a7He5irPgwroAR8bEYdXPK4v4=,tag:tVxJg8fSGwZ1ns+onteqTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFajB3bHdkYzZTdjZMOHBS
            a2t3LzhVWDNnYWpVYTJMNzFZN2FiZGVaVGhJCitoYnVxSU1aaFhrb3VGTHJwV3lX
            U2JScGNCNGtvTUN4Y0RhRmdkeTZEcU0KLS0tIHZPOWpYYkpxZ3Z6dGxkdC9IZVB5
            OU5iVjdHUHpsWFlqbi9kSTNzVG1uS1EKQFHjzqYVI11j78GoiwU8kHrZ9C4yOwcm
            7SOfK5IU5nnReBtWGs7AUl5ROL9tg/gqiFyCQe3OFKzREQlXlb8FMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
    lastmodified: "2026-09-19T14:38:13Z"
    mac: ENC[AES256_GCM,data:uYW5GQMIPYWzCyyCdH5bV+dAY2NtApZ/ZlXQAiGbzbnfVXQOBKq4A6MzlzD03O5XkhIo/+NrNilCdesOJFBiYnYIjlXnVzYoZBOClAqOb4CfqNj3qHcLC5X/zbUnqYiPbTydS36FSP9TTWcTHHs9Mg/XziUS7bPutc8Sz5Pxu9M=,iv:Ha5Is8gdutbpgm/9GTg5+EyajGG25eseI1s6eoPAlxw=,tag:fapuacwbsw7vHJ1/F8X7QA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
