apiVersion: ENC[AES256_GCM,data:Aww=,iv:p8s7Hf+xM0a8YKAs0v3ud0N4bKCpglxUyBzObD6Nn7w=,tag:LsqwwbXtfMMrBEDxHz4UEw==,type:str]
kind: ENC[AES256_GCM,data:d9lorfip,iv:ea9z7BItvlsbebYPjCsgNcVJVUZLSMnrW2aSsL8+THI=,tag:w2U7hggYVqLdqbnIHeTAVQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TvqNjpxh/MTvOfWFBcHnNg==,iv:7f4QyCzDvPq3qSZsgh14yifDxi2GEfjsaIGNPGJEdi8=,tag:ysbJ6aBtuuTpU0kMdJ5Oag==,type:str]
    namespace: ENC[AES256_GCM,data:lT4=,iv:bxJPUR3q+fH5M8pOK6QW7H3LstHzJQzyht9xgI94cZE=,tag:zbyGYqbEnvX0Up1Wg6gsQA==,type:str]
type: ENC[AES256_GCM,data:eyslQNVV,iv:7xFpeLIl7vaTPgfUzoryj6r/g72oQYMXWW9/S/P3c+0=,tag:y3TwzszsNg4glCuD+UjQZA==,type:str]
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:BY29pPhw7GNJayzmP4zjcnqtM3Hhul62MtLSEhv9XEg=,iv:Sl7mWZJZv8e8DMKKVzGFSRXJXYrJwGHZcpECnxJTMNU=,tag:XB1fLFCAF0CX1Mmra6tYkQ==,type:str]
    OPENCODE_API_KEY: ENC[AES256_GCM,data:oiO0Xuh7W8A6nCrGAkxQ079iZuhw,iv:hUJw9qSzRscPHNT3XreVDJuMJpepMOo6bcYwf6VJ9ZM=,tag:YVr3j64TWH4QnFDQVMENrw==,type:str]
    ANTHROPIC_API_KEY: ""
    OPENAI_API_KEY: ""
    GEMINI_API_KEY: ""
    OPENROUTER_API_KEY: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4clk2Q3BxTE00eS9PSjA0
            bEcwTlJ2SU1yTlhKU0VzTUM0NXVtaGlET2hBClJXTWhxcXNSWHdpUFFNZkZuK0w2
            cUpPNXpWWE01MDNrbThoT3c2K1RwbWcKLS0tIHRSN3lWdlFqWVErRDlPdkhYdHpq
            RjdqVTVBWUd6MjJLcGNXSElSMUc1a2cKWSVOSg8DTduxW8W/m1fxnrABG/oXpFul
            2HW07gNJVbYzEgf+k/S2gfuZPjVWP4sj/o+ZTt5eC231XaNsRQ6raQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
    lastmodified: "2026-06-23T03:11:41Z"
    mac: ENC[AES256_GCM,data:y43Umcmtvl+Qx9eKbs62v5E/2SWYFM3lCFLZLkFx3hMLFTKYk7sRotwISiorIwwiCVhRYmv8HtHmJidHlWIVonpTv9w/Qm9CsRZsraIV5ZtuvOl05rVMpS3GClqTYVruCCouhz4w7SzbHIkMMT2/lIpOmn1ki8KjrOOFTEh0akU=,iv:eQ5K08IlCg22xsRtUEkfbo1lFwq3BkfATG05zrLllbY=,tag:FR5C3vK2CfbnGUWz3igf/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
