apiVersion: ENC[AES256_GCM,data:R0M=,iv:uB5l2f+LdhXm6kfQsX4bIWe3ZvmELedmnf3qSxcUU9I=,tag:eZ/EBrqIgKMkDsa1rLPJzA==,type:str]
kind: ENC[AES256_GCM,data:Tyxbe/xt,iv:dOxfeirg04NDo86t0BpTu40nWQL5IhA3VLrPeqpKJ7E=,tag:sEEQTQeDuQV9Dt2DDJNWag==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EJjpG5uZQOBjS6oH8YNojw==,iv:W2ewV+O/0NJvZ3Z0ot0rea36ZTIdB/gYRz9BaIEDPkI=,tag:6nTE6x9S9RVSsASSYaEbrw==,type:str]
    namespace: ENC[AES256_GCM,data:5gc=,iv:qZQzOM/u4FgUN8Y0Ur02gW56dT2/jp7TCr/STf4lq4Y=,tag:diWKeILiNmeJtgrFT76X4g==,type:str]
type: ENC[AES256_GCM,data:tXj18nuB,iv:6bZAegPnr06vX6R9ItXKWrVo/7QAG9z1sWSnJXpfKbY=,tag:0ltgJOzi88PIWBTOAvIOmA==,type:str]
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:vIxNjGOjcy9CqEWo+eGKazeF0cS4qqSbq3rhN4TUI7GmDfJCdZ8waRIWE/93VuSBbI9YCtv6jrVI8rLsjN7aMg==,iv:+scjrZHXympb1m/JwdZmqAGJ/BHtJP8p25Bmtu1S2uk=,tag:8urnPSx3y58/AFBc24iqzg==,type:str]
    OPENCODE_API_KEY: ENC[AES256_GCM,data:mGYKlNv9n6RNpOZf7ggQSA7oX5aTJjDLf5OXgNoFssh6VcK35OPgeRiR41bOJFx0otLh8VgOVSlV0ImeM/zCOSANew==,iv:2tzD11pUh88W9h+CSxaGMIC7C+GYkEl+LHn/0i50cts=,tag:+L8zSdHXdEzC3cf3g46uDQ==,type:str]
    ANTHROPIC_API_KEY: ""
    OPENAI_API_KEY: ""
    GEMINI_API_KEY: ""
    OPENROUTER_API_KEY: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RjRBeG9TU2U3M0dWRzVE
            UytMUTJPWC96WitTRFJqa0poSFZ4bjJyM1RVCkROSXp1Zm5ZYk9aVEc3YU00c25M
            aHR0TDV3Y2FyUWdpZVhhWVdBUFozWlEKLS0tIEVNQnBGbFhEcXlqYTZWemdOMmJu
            L1V1c1ErQ0lOb2pjTzN1YUc4WTM3djgKj2PbBiMNxb+MZpCR1vFdAFsAaZGG156c
            Lxxuh9vgicmZUzTbGu9ER257QOjONsdLZysqThKd7DBYlMl8ufBkVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
    lastmodified: "2026-06-23T04:00:31Z"
    mac: ENC[AES256_GCM,data:xBmdYuSrEMT7hpE83vpBWUzxu6GqYc3smdE8NqU6Lg+p4ufLNzxEJo5j3YWtyIhmAjTUMTVoqNTH6S7PzMUd4CEcM2MlePKJ4nEj8VMmw7iGxH+ajnR7kT4UIRoaOKMbiqAW99x+pvC8NRLzaITcVNFtBHMF9YhUr2i1ktW9QQE=,iv:1tlawThI8zuklb6zWJKReC+s1X527672XpeIimArxFQ=,tag:+ZT+gA5/iexIWLg2ojVy4A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
