apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../infrastructure/traefik/overlays/saradomin
  - ../../../infrastructure/coredns/overlays/saradomin
  - ../../../infrastructure/whoami/overlays/saradomin
  - ../../../infrastructure/tailscale/overlays/saradomin
  - ../../../infrastructure/cloudflared/overlays/saradomin
