apiVersion: ENC[AES256_GCM,data:aJY=,iv:C3C5Lw9f92jGnfG5UUJJ4ag26hoL7zWV446tkDwGsEQ=,tag:tfxTFnNmo6gih2X3259mog==,type:str]
kind: ENC[AES256_GCM,data:wFPZYCFe,iv:iRYCS2c2Wp5GKxFgIqstnw0FZwV27EiLg9NvGXNubR8=,tag:twpI8NaTVm25s87zq91u5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:T6+F79ZIV72FgHQa5hI=,iv:T0urVk7yiU2Z1tKoUsQFOdJ9pVMncG1PAmEGhxGjo3k=,tag:dhkMlD43xw+zy+FJhsg3lg==,type:str]
    namespace: ENC[AES256_GCM,data:znZrU82zkqHT,iv:Rmk2wpYp7N8GAijtD+3cqR73KvgiIr2RVAJSdIL4PY8=,tag:ma5EcG1hzDtktxNn7du2Qw==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:SHgKISiov0mdOuLB/2rxZuM=,iv:i5nlg88//z4sBd0v1cKYcgwATODeZcNXtAnhd4Vq5S0=,tag:0PXNpoNY8DUnOCVjRtGCEQ==,type:str]
    client_secret: ENC[AES256_GCM,data:yMkFBttmVB7Y6RimmY0dsu/iRfs6Hgkd01Zt2ja5HBpV6DvbIz+K8gsCjE2/pwz3le7wn8fzMe+6xrtY1waWDw==,iv:0yD65wNCqxV3530iFNEc/G/ktX7Nd6uq1pj2t2fzM9U=,tag:GWKBE/NENMY3CjIsh5I48w==,type:str]
type: ENC[AES256_GCM,data:CTDcYuWk,iv:4aaY8McGjv3nKlUqjkE8ZgPzX9Dk2mWXKqaoHhpqbbM=,tag:MBU0CIg2Lu+33y9Di/0dzw==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGajNLUVZ5c21tMVdDeGZT
            WFJCS1pQOE83WlNrZENJcnJZYmsrbEpITGhzClR2WjhsczBOa1lZUzduWnRRNXoy
            a3B4WVJ1RFNORHVrbEROZzFrMnFiRncKLS0tIGdNSm16b3lTSDhNdnFEeG1BeUdz
            NmtHU1pkWThxam9WUHo1bDhRcTNWd3MK26uS/8M3k+tMWUwuf55D02rUXjGyRHXy
            3j/Z30v3c/Ow+cWPzqlH1vPW7h79fEwMh5A1jbp44dftBuNXsKk9PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T16:42:53Z"
    mac: ENC[AES256_GCM,data:y5DY9CQKCzSEnhAv+SIdsjCSbu0x3FZYyMPP54oLc7cU/ohBOCOOWy6nkeCgaUKk/Q8X36SsAm7C305zuIDACXbR/DP8f5N+dZP8mym/sfOqBZ8DB3jim2rRhIeqH59+VC+yPrT2aJmcbEzbEjht4/IKf522ui+J/7DDqDvd3/U=,iv:wHmfZBJGvwCTt89LwEzZaI+v9/icmNXQMrrkX+4Mhjc=,tag:Zxldc6T+l+j+mmWqKCOACQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
