apiVersion: ENC[AES256_GCM,data:SKs=,iv:pTTqp5K2yxGoBBbzsA97JPoYQ4NLXYG5Ol9F3jE5QWc=,tag:Deu35yxlLTHlTN7cDYTEdQ==,type:str]
kind: ENC[AES256_GCM,data:bb2VIles,iv:XD7GnMcUSuwcprvV5ckhr5mCRcRWPFLXRbVmRX7X4e0=,tag:gnMkUTDIELMK4dMqx2b3MA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:crdCEXHA2WvUZ5EZzwhp/d4=,iv:Y2p6uQTGUOqYABHhOJnXeupzWTzUgTY3eJy76rgIdYs=,tag:8pm34OPnlkq14TgYZNFGow==,type:str]
    namespace: ENC[AES256_GCM,data:yeOhN2slio6GhQ==,iv:pEsf4FxQrBomBiQQxbNtQh5t5VbJbqpt25zsy1ptqx8=,tag:BtpnKIJ14PYsXZfbWwfOkA==,type:str]
type: ENC[AES256_GCM,data:rZ6tzrsn,iv:F65yyIFOieA3TrzYNc1QEP2o3JJUPxVFjN8nXg7j2PM=,tag:cBIEmZn5U1p706t+FhHzZw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:ZxKtSUafhPrFAZZE73FTvfI6/I8CcopyzrmzOHSwLpTh1iTZfMDOwv2vzf7geNFjxGITF2iKfhszzoAxffcUPHaaT2BoybKIltuF8a0N2xYwoGspIARVhN5x5earg3SoLNi6DdxzkMhAfnU3BO4TcXRUGmOLXU/E8oaMdFVMQBAps4z0txkazGwl/Imw2iMsbOJnvv8pZTw3kQMCl3kzAo+4fF/KGjWQdQ/tr5daO4WVxSo3MjH5Ug+4jHtUw7v/lBivERG9vr5V/vPfkDYzy9EWoBucUsHTKBCrbbKm147ro0NhufGcCfLdi59FAgQQ,iv:WHYaCAJCAAHrZiMUMuqJJHGsosS6ASHiwzX3VZlaykk=,tag:Z7ngYNEyQwjMQQF7SMw9WA==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeUFCbFlQeFphaS9SU0Fk
            U2wvRDlkSzBiU0tVUVM0WS9PYmt2Yi9lY1dFClZDcDFXbC9hYVV1YjI2YXlVekQy
            U2NrL3U5MVc4WE9lZTN1SzNwa3dQd3cKLS0tIE01R3libU1lSGRsNlhZejJqVjVw
            RDhZVHh5Qy9HSVV4UHg1dC83Z2FzQW8Kq0SAa2Rwr+UVPD7kUbHOgzhmxqm/8TsT
            SIjexbUhTaCnab0V7UFs3q2RdMvmbHm9ZambSDoEt/TQcSYXQdeTNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T02:34:38Z"
    mac: ENC[AES256_GCM,data:bKlCNQNTeS3Rhizf+t5R/xWxS7GAgXLx4P/o3QAAHg4R5dILtZmxmhkkerbu+YCn1J6rr2dx6fTVGVzUKM3nmYy7YFvQ6+PqkfaEmiwugO5bXgbOTOa/Rm9HH93BDVGYtq/0xWo5Vk94hSf+0Epqj6S7yhjLgaiJY4kYhZiQrGs=,iv:ny0FSyauO0ca8vcPst7vGmMTBSUrOyqUDH2QFYHdsJQ=,tag:aOFDpCOHX2uQfdbLmnaKWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
