apiVersion: ENC[AES256_GCM,data:QBs=,iv:3uX700PjcoDsxpAwvkrg4Pi24Hu96r5fGWio4WkmOjE=,tag:VWB+X4A64Kzf7HAr5RrFlg==,type:str]
kind: ENC[AES256_GCM,data:JYcU7eYg,iv:HLARWAeH7C0D7oCx6RmfGTrljEmJ/uvDGE94EhlL0Sc=,tag:CbAgySx8sMn04PX2ecnUdw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XUo461Ms2u3uaK8Q8ZkTWZQ=,iv:b/M5WFVi4YOJYDQyxqVify0ZPLamVcv2fstsx9sS1B8=,tag:IvQmmIAR2m/5kcGIUNZG0A==,type:str]
    namespace: ENC[AES256_GCM,data:Ynvm3LQ20zHLkw==,iv:g4j/Thk69nuYSfhUK/Guz6OyHzU9dQurB3DA5g34Vsc=,tag:PG73f+/1iUFRQJIbkuUWHw==,type:str]
type: ENC[AES256_GCM,data:85LvarNF,iv:FSHYxgU3i6CEhRR5Dv09NjX6r6BRMKCnwO0N6IwHB8Q=,tag:Iv+bOVSbAWV0tnuoBS84zQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:pVLdZtAT2zDlV0VAHEKckc3yCcjYyDweFAaazBlA54nB/VSJ8aOLufIksY2lzLHesiNED8CZfPFcGbk6JSqEp6dwJrbT+SUzEZ7Rxdpx++SpgPKOG2x5ZLOJRLEDouGosI6HMARhyh81wudYV6qIGUMzt7V63Lcak6JuuLjPdC4EJra4ohdXkWW4t5azN4he3NO/Hnn1aPagVXa/AbYR/qa3RWKcULbG1xzQl4VaVY8C/s6XPS14pa1As3Z9z9fvy8MxnTj7h2FaGDt28C/BFS3lnl0VXn/OsYVG5spTZ7zloyiXradj9LxgdvrDjTTe,iv:JtP9LNstzKjBMUb8nvO9GDmx2PenCr8qwBpRKuYA0FQ=,tag:T2tPkNYNceIfpGf3bfFiAw==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcWRoSG56WVBxVk1rdVRT
            UFllaFpkQ2VtQXBJdk1zU0hTWkpCS3JYR1UwCmhCUEhNLzZObE4ybytDeCtxTkk1
            YnM5enBjTW9nQ2hJQURQalZXTzl0U3MKLS0tIGNxWXBDQ3MxL2VDM0t0S2s4Nk1v
            amlzMklHOFE1d2dBRU0rV1VKdDFhd2MKEkFefvsx2/nQS7bwqmBf9kUW6u9uvcem
            fKFcxAdVQalRUfXtMijaaiCmytLCHTtwS7FE4bCrlwpJolelGZXlNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T00:14:54Z"
    mac: ENC[AES256_GCM,data:8RCN3VrIGICVLelRoGudaV3OWe24WlCmbDtpb+8ZD5eRTgDB9h5WCVvozDCvTdCVoVlUGC6hUyF1F8ccMmb9L4eklctYsPq8BJx0UiERjJ/b+SLxyAdqoF4NUiIqK1y0Gg+q0Y7GkmBnlt7N8R5ip/osTCZkEecYGzmfydJYnxo=,iv:YBQrNbNdbO2j0tD0EPz1LhgwTn71+r58vXsBFxSLl0Q=,tag:xM5UV4RHAs8uWkhcuoeXtw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
