apiVersion: ENC[AES256_GCM,data:gtU=,iv:woK7PApuJZn/t3fKTuB2V1R+ZJmZ5Qnwo8fymOcRLEM=,tag:cQvMWH5togusLOtNfLhc0A==,type:str]
kind: ENC[AES256_GCM,data:OgCVwPoP,iv:GZvYxPycIh3RmzIA5Hf6Uya3mf9Q71ZBz3WIdkv62/w=,tag:tfCocmV2g8xcnW+wO48+Fg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Z5Ca2i6yfiJXJMPspa6VFy0=,iv:5LGsHyl5FtRcOglQd0cOtyUje+vuoIXIVGQGoEoV08o=,tag:4aeXxipVv9b0ZvdXC0+LFA==,type:str]
    namespace: ENC[AES256_GCM,data:Ym6vEWOg45TLXQ==,iv:9bmBb88gA+ckS92BYhLa/efniu5nDVlJApz0CcHpYEA=,tag:wIhqjc3X0llGueDAFrv34A==,type:str]
type: ENC[AES256_GCM,data:SOop44HN,iv:4W6LZeQBHyvfsvGuur7sdDmFVBDR+tbddiwKJf+1hzY=,tag:Np+gcWDgSPKlNEWXX3r+Ig==,type:str]
stringData:
    token: ENC[AES256_GCM,data:GKvIgrxQIzoqOGRu8KFAKkTdTV8fFrAC8hzOvJgqUsoL+RUmeXYrSvtokUj+DCzbNqYA4d38K5UQK15aRKRqWb3HfwhQ3yiy1jf2fvGtLTXQ2m0ESXoil8IX6w9H52ZsjIfQ2WDmoCAQN+o7+J5i2bZJ+45sXhUchpXUvb6tgV3TQ5Upxa1vr37HI4xxUtuXOployh7RlzNiQNPNkDjsnPEFkake+bYZNz+JFd7Mv97As1PnJHsqiorqj9Gk1fy7gBHWD54rb81xfkphXWMSI1cQBcNjPGH60HYimjKtpPJ4FdcBv2Ygu6dh1rjD16DX,iv:hTVS3TtSlkqX977e99NfMBb8CeuziED8hXSx3b0+0X8=,tag:iXpk3a766fYLNNNMK7kqlg==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMHRDaHA5dnZsS3ZpSGIw
            RURmNDM1c0JQNVNTZ3FpUFZFM1V2bmFrK1VzCmVTMGFsbVhvS3lMYXV1R3UwK3Jl
            SzUvbGJnT2liODZuZm5Dd2RmcWtEc2cKLS0tIFRRQlZFWlRoaDVEMS9obUlOcHgv
            bWFCWGM5b2VEYUsrNW5EN2dlQXBJVDQK3xsZ0mMmvWqZ/Fp7xwR9erUE4ozSP+YE
            SG1SJKNJxTvjHH4QRtF98hds+dzq25RJ0ddAYzMkslCa+ekbzDY46g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T02:15:20Z"
    mac: ENC[AES256_GCM,data:kKs69J0GYdNxY1TTrR10FQFI4YpHNVd7HCU62pdjzwUSiGj0RsInitJxeekzV3ODXcOkaitxlxJCL755zy01Typay5fApQntg5fQx+DkonfmA8RjkW1F0b7gwmGBhgNTaAbh1/WMsJ36mNWcaoOSzXo+y3WrdeoZBEaBIYnJ19o=,iv:wC5Ek9b5Yh6ehvD1yPs8xhexgS2BkQNauOunmOV4jMs=,tag:FD3eWc5Ns5fScx4oTmyAHA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
