apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: databases

resources:
  - ../../base
  - databases.yaml

generators:
  - ksops.yaml

patches:
  - path: roles.yaml
    target:
      kind: Cluster
      name: postgres-main
  - target:
      kind: Cluster
      name: postgres-main
    patch: |-
      - op: add
        path: /spec/storage/storageClass
        value: local-path
