apiVersion: ENC[AES256_GCM,data:KUw=,iv:h8oHlQHZ5BB20sB9nZp9+1l+kWVPszg+pW+v5e2Vd+4=,tag:UtsYtk7BS7JrObmJFT6n0Q==,type:str]
kind: ENC[AES256_GCM,data:EjH+jgo9,iv:GAyz/wHEhsAH1EoZSsmPJFHt6BDM3eHoYHIptG3IfB4=,tag:Vv8tGmBdJK0HTIcFheQM1Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Us4kSWHIwWZG2K/0eOau060wlWF4,iv:q6ZrzQdbvW4bGGIoUYgguqUfqYl6RP3hCy6ti34y4XY=,tag:UEK4Wcwbvk7gfR/1kL4t7A==,type:str]
    namespace: ENC[AES256_GCM,data:ReGoUM6HtcZS,iv:gv+p8cxipz201qP8515MRZD96YvZRCBqIYwyHjUZTnA=,tag:VocSkGOGDBEKpy3j7hLXvA==,type:str]
type: ENC[AES256_GCM,data:MFK/cjvoxGkVNpmeMjKr5ZH1GOAtYOKw,iv:wL2298EOQcopVtAUyB1DaqZPqH86/XONH8YAUP12PHA=,tag:chEbqpX1Aklr0q2wLUn0Qw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:jEWedr2brM6NTWM=,iv:Rcs5Pna9gaZvYfj3ikj+agjawZuV+8K0O2IOMdIEXBM=,tag:JrhpVIMQkR8MTTGIcuwdwg==,type:str]
    password: ENC[AES256_GCM,data:2DL6gxGqGjT4mcJf,iv:JxhWgeKKbGV2hd7J2cGyc9EdiS9RwsCeQwGGdIitXPM=,tag:+PhoonTxDLRIG3FYf5iLxg==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeTREUjFmOW1XZXUza1dn
            TUhkcFJSRFhrT3E0UjFNa1JOaWVZV2g5WUFvCk81L0daeGhaK01rYXZHa3hJZlBI
            WklFWWF0MFVKTDY1Rm1rS3RRRVhPZ1UKLS0tIEVEWUNxT0NLc1dLVHZud0gxenBG
            MXVuTkFFWkE2eldqYnBtTHI4cHlkeWMKG1O5YeJo6dQY0RnTjkXxR2kU0OVJT4iM
            XZ4xHIhTYDyIwyvHEBSp9d1dr5UYzekzpue5kms3xx5LwzTFQJ1GpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T02:15:20Z"
    mac: ENC[AES256_GCM,data:R4xmo4rsUCpPCLizzn6zjRaR7ROFm6KLwk4kx7h/YcIP37yPA4PexHQOnTPNqtcTqNC6X7ROIll8AmfgNf/OSuZFC2B5pHyCfNyzAazRJ/rZ5gk8DenV8PyZXRFVt2Vo3qoRo0VYQx3DSgoFXAIq1sxE5aG1dkWhJBEQUTULMOk=,iv:KC+zflYc+AXrV1bkHOfzNDPeywherc+eGOmuv2J+sPE=,tag:PUG5L4vhSG83TSFVlrF7nQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
