apiVersion: ENC[AES256_GCM,data:dLw=,iv:qSJPvWNrr5w+zz5SRbHvqs4i0ozV0MklnMxQu0YYmEQ=,tag:T5+WyWZFVKdypy25MioM4Q==,type:str]
kind: ENC[AES256_GCM,data:W2EaE6hW,iv:4bOhw4Yc3QcD2KhY3s1/+LztgONg59BDFkoOqGGjFCk=,tag:orgRf2O28qNc5SEM4PDuhA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5kFGZQab9Qt/BCabxlv6xf3roVP9,iv:SvkwxlqE/+Qmvco8BKyFZ+6qCusyESFGcUNCnhEAJw4=,tag:ceWxpiwCUn/P14zGVj1/ig==,type:str]
    namespace: ENC[AES256_GCM,data:F+UzJHzO58ew,iv:nZEmvLZBlHvcgkKBveQHJ4KDPVPvRYg6nQuZGLKuIHU=,tag:FdUvKp7qo0U8yTGoebFAmg==,type:str]
type: ENC[AES256_GCM,data:JssDEdzVQ+NWHp5jz0aAuuGq5rnFEbTt,iv:fDZQaRwLW3u6+FYYOflp7xOoHAYoPKNe1fvl8s4x1EA=,tag:sZ25KS2AKo+EPp7jv4Zdbw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:PO1T+o0LR2b6GTM=,iv:o/8egLVqt/h+hVY+OetmXCR+EIDIi/fn4ZG4OdtSw9k=,tag:/crXITxaY56exLd9DivWFw==,type:str]
    password: ENC[AES256_GCM,data:mmIDzEJ0keKwLKai,iv:jevUrx0PvKZP49OGaIeIO89LzwPrvGrgD3Wic+D5B8I=,tag:D6zpCbu5pgbiBYUVJ06Lxg==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVlhTYmxmS1lLYjNxS3pq
            b2tDYU1MdVVXckVxNVFOMHVOWXQ3L2xyTDM0CkVpdVc2cG1RSkJSMTVsSmViY0RT
            ZFBFbjNwS0d2UHRHbFhXV01CUHF4UW8KLS0tIDJNb2lxMlljUXk1cThqQm04Vktj
            VkxWME9lSkdiV3R3d3pzMEt2b0dHdHMKZB6wd+Vm1saNt7we94KgKqjlUG0NyXFk
            NttDc7HRxmS/ICsYsLbfNuSnfphleBmQrta4ykEoo1B7bSb6RiiLyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T02:34:38Z"
    mac: ENC[AES256_GCM,data:P+CL+Z7VpH2EA80xilgsB+gRCgtRPFdKazR1VuAjmdwzQ8EnWvakQRbpsKg0R6wCIP0gaGPBoHqZ6JP2ocJn+LWHwe26jtQNhQHeCzESeTt4rQ1J5WP7IgHLjNPjaJ/dWndyJ+Sk2XTbqEw5/JUMi7I+Q5+8CUDVB24tHR/1wDY=,iv:mcp1+a8Na01421uKJPuuCBc6wZMukGcx51u5KcKMk30=,tag:O2xGplVHzT/pssAZ57lwNg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
