apiVersion: ENC[AES256_GCM,data:ZAA=,iv:7g9f8SaOTQhzJ+Hjd0+wP6PDU/kEJ7dOnWtcJmEUGLs=,tag:DCZUJ+qTHXUAP6yWSuY4rQ==,type:str]
kind: ENC[AES256_GCM,data:Y6oH4Jdn,iv:FHqM/j4v9KU74ThOpJpG3SExXnaFnVVCVEimGFqMfZI=,tag:NXVydejP2b0DfRmmqRRW7A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NMxwS4BttXr8yZCx1pOmORQj3KzD,iv:NqpoFqU2SCCE/YWtSmkLr7cyQDjgggXqrFXAutwA7dY=,tag:tNDQI5hzwZq5ZXzkr/Fo4A==,type:str]
    namespace: ENC[AES256_GCM,data:I0DZiM3kUjhP,iv:lcRcL0fig2Y7Sh/PwR0bwS7AoPGiedbjplrv5nyeUsE=,tag:XGe7ZN/KxK9c7aRyJyGu3w==,type:str]
type: ENC[AES256_GCM,data:ZGPU5G/y3eS14H4mtO/vvMIpQ1aTeLkU,iv:LoUwrbtH8afSV2TIX0amq8/a1CtkXfjYqEGquzaUEqo=,tag:stwKGzrx/oIPa42FKdSD2Q==,type:str]
stringData:
    username: ENC[AES256_GCM,data:XGHI8jpq3OL49uw=,iv:JUwbVYII1ddBrwK6zCtfKtRmR1rPeLBCZwVzdgqqOYg=,tag:NuLSWflOCEtCueuY6Dycrw==,type:str]
    password: ENC[AES256_GCM,data:dN/x17su15q5pkd5,iv:Z7olrp1CL3RIg51NbrpDDl22eEaPnPJddC9OV6oXRzA=,tag:gtLoUrLQz3dx9tBHGxbx2A==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyM3FhR0xCdGdGVGpWVzdh
            clFKblN0QVlhcGhHVDcvVzVYMkFsUnB3WEU0CjczY1hlTTNtYTRyMytSOHZQZUFx
            RE5BcVhOcDc0NXFTbUJCcExqblIxZTQKLS0tIGQvMkpaU1N6dkhKUGZETmltWFN1
            S1QrYUVJR0hONFk4bXAzWkptTzRtSG8Kv5TbzhEmhpqvKerr4qeC6Z81vmLVIFDe
            Uq2FFloDyOxakHoMwwwvzdsL7YWFYVKSzXvz401mhCkWYP/qtLuRwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T19:54:00Z"
    mac: ENC[AES256_GCM,data:h1ZDwyXVOiQwhL0ShHGGcPaib9dSVn3FKLsKx2DhdtB3+kDSO5czuGkTC7JIVxB1ZGT48DlwR2Nfqh73lQCGuDFRSFlVPlSpWhqwCVRym8nDonSeiCZMkLL0jNUEpsXIr50e9oCU9pgrs6IFFjfS7wJOt1xOK54fbK/LWZdJDvQ=,iv:5r8Y8v77gTPTm51Lyya0KGqmgWU7ik0d2Zp1OvViKS0=,tag:1lOntbD5V8QUBmODY+04Tw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:ZAA=,iv:7g9f8SaOTQhzJ+Hjd0+wP6PDU/kEJ7dOnWtcJmEUGLs=,tag:DCZUJ+qTHXUAP6yWSuY4rQ==,type:str]
kind: ENC[AES256_GCM,data:Y6oH4Jdn,iv:FHqM/j4v9KU74ThOpJpG3SExXnaFnVVCVEimGFqMfZI=,tag:NXVydejP2b0DfRmmqRRW7A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MROojVrUq9h8r1B6bw==,iv:DPhTyOcacQQvDg536PexXpiNQnx+jPehhSscKxi8mic=,tag:scr2bqMi1gUWgaP072jn2g==,type:str]
    namespace: ENC[AES256_GCM,data:I0DZiM3kUjhP,iv:lcRcL0fig2Y7Sh/PwR0bwS7AoPGiedbjplrv5nyeUsE=,tag:XGe7ZN/KxK9c7aRyJyGu3w==,type:str]
type: ENC[AES256_GCM,data:ZGPU5G/y3eS14H4mtO/vvMIpQ1aTeLkU,iv:LoUwrbtH8afSV2TIX0amq8/a1CtkXfjYqEGquzaUEqo=,tag:stwKGzrx/oIPa42FKdSD2Q==,type:str]
stringData:
    username: ENC[AES256_GCM,data:laur,iv:QSZyNarZSubf8ywPzItDnNrHfPkHMGAnM6z+mdQOUck=,tag:NcYolIWWWM0rDgQfdXeWCQ==,type:str]
    password: ENC[AES256_GCM,data:PAye8p4Domu37TmK,iv:XlWY3v0uxGA9SNKGYGR4Q0XWr21Wt93yJauXpSH10HQ=,tag:G1ywm0dctIm9Y6yf3s+eqA==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyM3FhR0xCdGdGVGpWVzdh
            clFKblN0QVlhcGhHVDcvVzVYMkFsUnB3WEU0CjczY1hlTTNtYTRyMytSOHZQZUFx
            RE5BcVhOcDc0NXFTbUJCcExqblIxZTQKLS0tIGQvMkpaU1N6dkhKUGZETmltWFN1
            S1QrYUVJR0hONFk4bXAzWkptTzRtSG8Kv5TbzhEmhpqvKerr4qeC6Z81vmLVIFDe
            Uq2FFloDyOxakHoMwwwvzdsL7YWFYVKSzXvz401mhCkWYP/qtLuRwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T19:54:00Z"
    mac: ENC[AES256_GCM,data:h1ZDwyXVOiQwhL0ShHGGcPaib9dSVn3FKLsKx2DhdtB3+kDSO5czuGkTC7JIVxB1ZGT48DlwR2Nfqh73lQCGuDFRSFlVPlSpWhqwCVRym8nDonSeiCZMkLL0jNUEpsXIr50e9oCU9pgrs6IFFjfS7wJOt1xOK54fbK/LWZdJDvQ=,iv:5r8Y8v77gTPTm51Lyya0KGqmgWU7ik0d2Zp1OvViKS0=,tag:1lOntbD5V8QUBmODY+04Tw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
