apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-main
spec:
  description: "Main PostgreSQL cluster for Zamorak"
  instances: 1

  storage:
    size: 40Gi
    storageClass: local-path
