apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    app.kubernetes.io/part-of: apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: networking
  labels:
    app.kubernetes.io/part-of: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    app.kubernetes.io/part-of: apps
