apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cloudflared-saradomin-secrets
  namespace: networking
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets.yaml
