apiVersion: ENC[AES256_GCM,data:2SA=,iv:scLN8a0VQrxfv6bGEuz/F10dyGgJxTdLiZ+UXKgcATA=,tag:1hlqOMB/++RObYv2KF03Fw==,type:str]
kind: ENC[AES256_GCM,data:rYu12qX2,iv:MS1wlhpWS1PeRi4RZ9BDa8vJyIl2FjICIOTiHhCRUhg=,tag:QQ6Hf6hzABPxjV7XqCs3fg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kB5Nw+3CslD4PLWG3JOksO4tz2c3Pcbmtob+,iv:QXCsz5v1gCJ+ofb5P03NJJvf71D2Qe3eEDGEQXTPuuU=,tag:uF5J6wxEl+1xfoLuwWwqYg==,type:str]
    namespace: ENC[AES256_GCM,data:sYQQJvUeQZZpLg==,iv:vi7vVAGaN8FZgyv1zm5h5C+FCwL4LSyMbqoi73Ua3ro=,tag:NQQKXMylmTI2RKMQQ+hEkA==,type:str]
stringData:
    token: ENC[AES256_GCM,data:H+28Yi/Qu9P0tplvyURD2Wy58n5PFAL2Yhch6LiSeNntSrJqkP/8R95J9/kRo6oFeIhBxaozhNWtxc0tTZdELq33UOVptqb7mrFLa5BX+V41ik8Stkj1CnqKQ0KAa/9n6tbdJF/I44Y+L0GsWPbeJ3f1tyRbVtte/mJjeuEWPIBK1R9q42f3abXuADs1ErNiee/Se1VA61hUPc0A5AFfYEtyYoZ5jVM3XLgKbnhAEH63PLSeas2ens41OT7vg7yrkSDrJNkkxRXv4jZbcqwhYMZQwFZk++lnaRdUWW7Ftci4EmQNcIXS+NtUbtp2kIX7,iv:DBD353RHKx3LPSaod1MoWW7O4k8Q0QrkhgczyutW5rI=,tag:swwiyKKafsJQHPwuB49T7A==,type:str]
type: ENC[AES256_GCM,data:qYRYbJsm,iv:+rBP/ziVU7YaOCG9E2PXQTy39I6B90CPbi1ro+dH7tQ=,tag:g+WGgyIH8yebjbMjagcNtg==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5V1VUbXV6Z1hCU2k2b0lI
            TzJMd2NoM1F1VE56UVhmYjRRa3BKM0NvVUhFCjJxMEQzZ0hYcUxMbllhOTZ2R1NO
            VEU4elptM0MzVWRkV3NINVM2Z0IycFUKLS0tICtKVlBGM1dXZk5HYmxCS29ib0hQ
            WFpnS1FpQzlvQTBOdkpOZWs2QjV3VnMKprSF99VAbqqEXs1oBJAJm9M/65cV2y/s
            LjFsjYM1Yty8nbQAqg69HmqvUAmKPgH0dWPZNgr4jD5ji4qe83nOoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T14:57:22Z"
    mac: ENC[AES256_GCM,data:mUYCG0a6u912y73GhlZkY0LVU9cdxY1tMy7lDIFoz2qGA8v7lbT7friEGtTvP/JAWfuWLG5Db9Cqi4KXK28Du8tkVJx28ARyXaao95yjcoeMezOQJhh6vRRGb8cwd8ibZsLnnD6/CM0HTlcMBpMnO7MX4DOQN9mv/6BwWdw2R1E=,iv:Zc3+jc2ZfxVKJ3b4H8AEtsu1uYwjaG3GmN0QM1L3ShY=,tag:e4TH7D+s2GuR7wWS5txFRA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
