apiVersion: ENC[AES256_GCM,data:+R4=,iv:8ERyWoF8kOmJ6pBB6B4T6LeYNDS0Ht8z+yG6qI/iTgU=,tag:dtnXqy/2rBIRU9nvszxrhA==,type:str]
kind: ENC[AES256_GCM,data:6riiQZFJ,iv:2tFXzKqYf50XwUZ/94ZFBTXxg6z6sz/qQXpnSPy+JbA=,tag:JNu6FWatZJZt4kAW5JByWg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2IUeLmCDPU2Dj+tU2aXb7qg=,iv:dpT/0646oAIGR58S7M8xsMXoq7W/pTGu/7yRjnLSsts=,tag:BZV4BIlKPaWNuNulpRGebg==,type:str]
    namespace: ENC[AES256_GCM,data:uira04GuCzQo2Q==,iv:X91pTBVODvZVMPTOuviDUOv7QnqpyCfVYkHGwnpNRw0=,tag:40KB9hxi/7e27t0RbZZfSQ==,type:str]
type: ENC[AES256_GCM,data:DIIEEeYF,iv:eSbrDdyyheJSE26a5X3h9z9pQ2xP88lVeNAyAV6fGH4=,tag:SOo4YdKoHYMTLf2yVdwzag==,type:str]
stringData:
    token: ENC[AES256_GCM,data:VUxeABQvcf0egl7F4P5ThW7I6+//AFQU7+GCZcjUPevNt1B0mlzh6ALHVDoLs0/PfdT5AWXo9OhqSRLBZJ+6GrpP/CuRzq1jjqCg4ipg3Jw5nAVY7WMBWR9r3adboPNXC9pFjD6qJNrJ6dY2hzdHB8yej7TYKsGKW5RtwjZyK1Ysi/Rv1xkOpCCh9+fjVA+bpXMC1AU5jkLW37I2SLO4UrdkpRkKB8kh05dmkrpjAhGcxkc2ZLeUnMs6++sKTHhfNDEQBQilJnexnqLY/CcZx/bYOpcZg2GFUd5kqFjUkXLj49KdRO30fUgrZgBBwt1s,iv:v6aDBcmIMWZvYPHWEd3SCorQ6ZnYtwwS84Q4+LQCY9c=,tag:QnYW/1FGmdWcDzGF+nqoVg==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcG02Z2t5Qi9Fd0EvSGdX
            K3h4ZElDTjhzL215a015OEVMbFhvL0sybFYwCmxXUWJtQ2NUb0lWME9YYVh2b1Ft
            QlorZDJMc2hYUnFneE1YbG83ZmxsdWsKLS0tIE5HN20yTHF0RFQxVlR5OXZqcVcv
            ZmdqbW5vZE9DTzcxemFqMW1nRDFnRDgKZdJVVpikPY+SVwmZ0Ay/ptyXQkn04iCz
            BlANv54u2hG1uOVfnJqWDNcaR0iQozLskRGiLMBIRd39aIbZn78iTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T16:42:53Z"
    mac: ENC[AES256_GCM,data:l3v/ZDXkh6yCxTdrnEODpufrx0RPZ5CR34HmU8Xq8oiwRh8jcKFF4M2fWTL7j7f4jqze1+avHYknGB4C31O9gMQMD82EIKRbGUh78DIhR8qrie9tSP566CuodMRpKJE9uDysgFRtrN1ZO9JPv+dEfuigG8eVcUVrf37O7wKcvl0=,iv:r7gXIORMNZMT0rXl8mr7SsgONuB6Uz3btDZHPLpEK9Q=,tag:VLuh5rjmrdHbPFTLjqynkQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
