apiVersion: ENC[AES256_GCM,data:ZMM=,iv:MQ+ez3YAgusBlmgy1Y/mUiwZ+Igin2y/mzwx3nN+7/o=,tag:Gt1s7BCq65p/TJ9VigvEIQ==,type:str]
kind: ENC[AES256_GCM,data:EkugBZQc,iv:MLqf8/9zKTkZlbPlv8ITv/Yh8FuCjerQcebGS9v+VE4=,tag:cwwr3SH/o2NGTlAGs+pk9Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QFBYbhBLvxrSFIJn,iv:Kx8oqJpotIje9I4bRHTvownESi+O1sLmDEeLQXaiv3g=,tag:vTuw27VvJ87XhP2S/FIPCw==,type:str]
    namespace: ENC[AES256_GCM,data:G+1PgA1/21u2,iv:WJjiaMpqxJjSQcccJi5fElDqDdXAf3oGShZJLdakUqY=,tag:6MBj7CSiZjoFq2ysyonhYg==,type:str]
type: ENC[AES256_GCM,data:ZHMsnZOJ,iv:R5w/ALo+cWWmkjEFQWE85Vhg02Levsp7u4SHRxQN/lI=,tag:KtRn/hbxLGSC//ux9YruGg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:7l7/HRjFOQJ/9MHcmu8OoaCDw1AwHRwx76EOdTnn4Eo=,iv:MYQIXpgcgsJ//9WBw1aWeWvuNtJEQvsGkt+OzWwquFY=,tag:e30ZDWvC6Lnsg3R+IaT8TA==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUlpiZzdhbVJTV0ZGZWR5
            eFB0ZmhpUzZ4UzdaVkNFVVhrSDFSZEg3eFJRClpOc3VCWERHU0JtQVd1Z0NiNm8r
            Q1ovZE1jajNoNjAvYTQvK1VMN1pXZ0EKLS0tIGEzSWJUSTBpY2RRMThwZVpwNkkv
            bkErejdSZTdYNnRyTEJyRWo4eUc4bzAK3L+cIqsGecw7JU06rarFW/dGYxvd1QWk
            zI22++AWgp5tWRKtPizNVKIJL28ZMuQbxrlExroP5TinfIkGTanrHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T03:10:21Z"
    mac: ENC[AES256_GCM,data:CETmDVEhJE5XdAW2pJP39IckeV+u/Wq2Udi5XjuvvUBVpv5GF8qRRC80FEBZnP6TmwUAd02lGEXHfxv14mUKqw/RMPBxY3mImZS8Uf6MWtchGe3tZOQXrh/Pm9kyfWkgbQH0eDgMenY76NN80Fc9+Y0IfTsZlpbWEUkEi9lFxHA=,iv:VouVau+pI9KyaeK/NWMfYRzUFnf0DDXv7K8LKi7Ia9A=,tag:U56J5kCudmZACJAB7O1prA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
