apiVersion: ENC[AES256_GCM,data:G00=,iv:kOXTvapbBUglvM17pMul6YtFkSHi7e9iJWcGvRSMVMo=,tag:x8fv/nvgSQgOaAVf8BSQMQ==,type:str]
kind: ENC[AES256_GCM,data:c+licqTB,iv:Gawc3HtYcXlzArrR71dV2R41o+Q9/JsGh/bOTburIko=,tag:j9sTTjKHn2HF7c2ig5NijA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dFLBIYcwOZ+/fSGs,iv:waK2RP+v9gMhXQkmNwvqkGyVQ8eFzxaR8rE6kt/oOzI=,tag:eQAIHrSP22SIQ6iSPF+AgA==,type:str]
    namespace: ENC[AES256_GCM,data:CGXpumMraT3m,iv:GvuZVnNVRxoYy8YWSXOldzk3h1htkLPktqSqVBsO2p8=,tag:nDRMhQ7CVAiBSftuycUspQ==,type:str]
type: ENC[AES256_GCM,data:qxKurw0T,iv:fF6k4yDbv3sHlARJxsB5zKkgdFCAzSFRwndVGrF/ZmE=,tag:Kny3dJBWhGJJOciOKYbnfg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:mTOFyaeYXSERwfKiY+X8YVBimFYLE9y6/fPOZrPDGso=,iv:jnAZ1VmJuPVhRr5JtoLtvHrpHbSxFdifIqT6R6wzJsE=,tag:pBgIneuNtV++ddHWn4I7YA==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWVpSclE3R2VMdTlIN1lK
            MXdzN0prYjkrNlJNRmJJMC9FQ053K3hHZVhjCmRhbXNOd3E4dXFZSXRVR1Fra3Q3
            K0NsNlpUeC92b3RXRG1FcWt2NHJNRTgKLS0tIGx2SFNlQW5seERwZEFxb2l0alRw
            VlErTWNlSXFzRnFySStkYmRpQlBXT00KDXquf1WWEr83z/vqyhBz96sXnSPdRmEs
            WWJpBZGFjzMVXpGkm07YWmTHcNiY46Dowi/UO7UJ8LmGpN/k9LYxAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T16:42:53Z"
    mac: ENC[AES256_GCM,data:2nJsMVDOL6AOZoHpfvoxVAFNERExUlfsQPN9MIoLfzH4rZ8cDZ4pkU4rqu0Zj51eUJvj6KhhMGfimC5N0FTxvZdiQeOtGzpMXJgKBzvLqx+wLw6zpaqZcl/zf3YRc8c/um/9i6BBdHp1QpXfzaVJHTrROcg7pZ8gpJFR/HBdXak=,iv:2xsaL7cQF5VUQHYX1MpfN21QiSqgSbHdm7ed0jnKKmQ=,tag:3ySs3voflvWeHyRgKIltmw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
