apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - infrastructure/traefik
  - infrastructure/cert-manager
  - infrastructure/observability
  - infrastructure/adguard-home-dashboard
  - infrastructure/whoami
  - infrastructure/tailscale
  - infrastructure/cloudflared
  - infrastructure/argocd
  - apps/openclaw
  - apps/media
  - apps/aerofoil
  # - apps/docling

labels:
  - pairs:
      gielinor.felipe/cluster: saradomin
      gielinor.felipe/site: home
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
