apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: zamorak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  description: GitOps-managed workloads for the zamorak cluster
  sourceRepos:
    - https://github.com/FelipeMalacarne/gielinor.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: automation
      server: https://kubernetes.default.svc
    - namespace: databases
      server: https://kubernetes.default.svc
    - namespace: networking
      server: https://kubernetes.default.svc
    - namespace: security
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
      name: argocd
    - group: ""
      kind: Namespace
      name: automation
    - group: ""
      kind: Namespace
      name: databases
    - group: ""
      kind: Namespace
      name: networking
    - group: ""
      kind: Namespace
      name: security
  namespaceResourceWhitelist:
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: helm.cattle.io
      kind: HelmChart
    - group: networking.k8s.io
      kind: Ingress
    - group: postgresql.cnpg.io
      kind: Cluster
    - group: postgresql.cnpg.io
      kind: Database
